export const ITEM_FLAVOR = [
  {
    _id: "5e08da62c487cc01bfd4e8d0",
    text: "This looks like it once belonged to a dwarf.",
    typeId: "helmet",
    model: "ItemSlot",
  },
  {
    _id: "5e08daabc487cc01bfd4e8d1",
    text: "An aura of mystery surrounds this object.",
    typeId: "helmet",
    model: "ItemSlot",
  },
  {
    _id: "5e08dad6c487cc01bfd4e8d2",
    text: "This body piece looks like it hasn't been washed in years.",
    typeId: "body",
    model: "ItemSlot",
  },
  {
    _id: "5e08daecc487cc01bfd4e8d3",
    text: "Someone died in this armour.",
    typeId: "body",
    model: "ItemSlot",
  },
  {
    _id: "5e08db08c487cc01bfd4e8d4",
    text: "Fresh and pristine, this armour has not seen much use.",
    typeId: "body",
    model: "ItemSlot",
  },
  {
    _id: "5e08db3dc487cc01bfd4e8d5",
    text: "They look like they have been cleaned but you can still see hints of blood between the fingers.",
    typeId: "gloves",
    model: "ItemSlot",
  },
  {
    _id: "5e08db5ac487cc01bfd4e8d6",
    text: "One finger is missing on the left glove.",
    typeId: "gloves",
    model: "ItemSlot",
  },
  {
    _id: "5e08db5dc487cc01bfd4e8d7",
    text: "One finger is missing on the right glove.",
    typeId: "gloves",
    model: "ItemSlot",
  },
  {
    _id: "5e08db79c487cc01bfd4e8d8",
    text: "Old and dusty from years on the road.",
    typeId: "boots",
    model: "ItemSlot",
  },
  {
    _id: "5e08db8cc487cc01bfd4e8d9",
    text: "Fancy and ornate, these boots are for special occasions.",
    typeId: "boots",
    model: "ItemSlot",
  },
  {
    _id: "5e08dba4c487cc01bfd4e8da",
    text: "Something about these boots tells you they are fast.",
    typeId: "boots",
    model: "ItemSlot",
  },
  {
    _id: "5e08dbbac487cc01bfd4e8db",
    text: "This weapon is rusted.",
    typeId: "weapon",
    model: "ItemSlot",
  },
  {
    _id: "5e08dbcbc487cc01bfd4e8dc",
    text: "This weapon is polished and looks like it has never been used.",
    typeId: "weapon",
    model: "ItemSlot",
  },
  {
    _id: "5e08dc17c487cc01bfd4e8dd",
    text: "There are multiple dents and scratches on this weapon, it has seen years of combat.",
    typeId: "weapon",
    model: "ItemSlot",
  },
  {
    _id: "5e08dc39c487cc01bfd4e8de",
    text: "This weapon still has dried blood on it from whomever was its last victim.",
    typeId: "weapon",
    model: "ItemSlot",
  },
  {
    _id: "5e08dc57c487cc01bfd4e8df",
    text: "Sparkles like a star.",
    typeId: "jewelry",
    model: "ItemSlot",
  },
  {
    _id: "5e08dc6ec487cc01bfd4e8e0",
    text: "Looks as if it was a family heirloom.",
    typeId: "jewelry",
    model: "ItemSlot",
  },
  {
    _id: "5e08dc82c487cc01bfd4e8e1",
    text: "Mysterious.",
    typeId: "misc",
    model: "ItemSlot",
  },
  {
    _id: "5e21e448f72b50317c3ce1d3",
    text: "This potion’s clear liquid floats at the top of its container and has cloudy white impurities drifting in it.",
    model: "ItemBase",
    typeId: "Flask",
  },
  {
    _id: "5e21e46af72b50317c3ce1d4",
    text: "The potion’s crimson liquid regularly pulses with dull light, calling to mind a heartbeat.",
    model: "ItemBase",
    typeId: "Flask",
  },
  {
    _id: "5e21e5a0f72b50317c3ce1d8",
    text: "A disgusting looking weapon, covered in blood and grime.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    _id: "5e21e687f72b50317c3ce1da",
    text: "This bow glows dimly with a pale, eerie blue light.",
    model: "ItemBase",
    typeId: "Shortbow",
  },
  {
    _id: "5e21e68ef72b50317c3ce1db",
    text: "This bow glows dimly with a pale, eerie blue light.",
    model: "ItemBase",
    typeId: "Crossbow",
  },
  {
    _id: "5e21e695f72b50317c3ce1dc",
    text: "This bow glows dimly with a pale, eerie blue light.",
    model: "ItemBase",
    typeId: "Longbow",
  },
  {
    _id: "5e21ea87f72b50317c3ce1e4",
    text: "These gloves conceal three extendable bear-like claws.",
    model: "ItemSlot",
    typeId: "gloves",
  },
  {
    _id: "5e2642b94f6bdd7ef1745260",
    text: "A sturdy copper brown belt lined in coins with stylized storm clouds and lightning engraved into them.",
    model: "ItemBase",
    typeId: "Belt",
  },
  {
    _id: "5e2643ab4f6bdd7ef1745262",
    text: "Wearing this loose garment on your waist allows you to gain some of the powers of powerful monks.",
    model: "ItemBase",
    typeId: "Belt",
  },
  {
    _id: "5e2645f14f6bdd7ef1745266",
    text: "Crushing is a way of life.",
    model: "ItemSlot",
    typeId: "gloves",
  },
  {
    _id: "5e26464a4f6bdd7ef1745267",
    text: "This magic armor was designed and magically enchanted by an ancient warlike tribe, hints of that once-powerful sorcery still linger within it.",
    model: "ItemSlot",
    typeId: "body",
  },
  {
    _id: "5e2646dc4f6bdd7ef1745269",
    text: "This weapon is said to break hordes.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    _id: "5e2647a34f6bdd7ef174526b",
    text: "If you treat me nicely I will be sweet. If you treat me roughly, I will get mad.",
    model: "ItemSlot",
    typeId: "misc",
  },
  {
    _id: "5e26488d4f6bdd7ef174526d",
    text: "The metal is forged with a long forgotten method. The special alloy makes it very durable.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    _id: "5e2648924f6bdd7ef174526e",
    text: "The metal is forged with a long forgotten method. The special alloy makes it very durable.",
    model: "ItemSlot",
    typeId: "helmet",
  },
  {
    _id: "5e2648ab4f6bdd7ef174526f",
    text: "The metal is forged with a long forgotten method. The special alloy makes it very durable.",
    model: "ItemBase",
    typeId: "Plate Armour",
  },
  {
    _id: "5e2648d84f6bdd7ef1745270",
    text: "It's said that the enchanted woods can help living creatures if they're lost.",
    model: "ItemSlot",
    typeId: "jewelry",
  },
  {
    _id: "5e2648ea4f6bdd7ef1745271",
    text: "It's said that the enchanted woods can help living creatures if they're lost.",
    model: "ItemSlot",
    typeId: "gloves",
  },
  {
    _id: "5e2649084f6bdd7ef1745272",
    text: "Tough Love.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    _id: "5f1ed013493c895c310de659",
    text: "We can no longer afford to live with desire.",
    model: "ItemSlot",
    typeId: "gloves",
  },
  {
    _id: "5f1ed02b493c895c310de65a",
    text: "It can be difficult to know where to begin.",
    model: "ItemSlot",
    typeId: "jewelry",
  },
  {
    _id: "5f1ed02f493c895c310de65b",
    text: "It can be difficult to know where to begin.",
    model: "ItemSlot",
    typeId: "boots",
  },
  {
    _id: "5f1ed06a493c895c310de65c",
    text: "We believe, we grow, we are reborn.",
    model: "ItemSlot",
    typeId: "misc",
  },
  {
    _id: "5f1ed070493c895c310de65d",
    text: "We believe, we grow, we are reborn.",
    model: "ItemSlot",
    typeId: "helmet",
  },
  {
    _id: "5f1ed07e493c895c310de65e",
    text: "Visitor, look within and empower yourself.",
    model: "ItemSlot",
    typeId: "body",
  },
  {
    _id: "5f1ed086493c895c310de65f",
    text: "Visitor, look within and empower yourself.",
    model: "ItemSlot",
    typeId: "helmet",
  },
  {
    _id: "5f1ed093493c895c310de660",
    text: "Without curiosity, one cannot heal.",
    model: "ItemSlot",
    typeId: "gloves",
  },
  {
    _id: "5f1ed099493c895c310de661",
    text: "Without curiosity, one cannot heal.",
    model: "ItemSlot",
    typeId: "jewelry",
  },
  {
    _id: "5f1ed0ca493c895c310de662",
    text: "We must not change ourselves, for it is others who are in the wrong.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    _id: "5f1ed107493c895c310de663",
    text: "Power is the knowledge of purpose.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    _id: "5f1ed110493c895c310de664",
    text: "Power is the knowledge of purpose.",
    model: "ItemSlot",
    typeId: "body",
  },
  {
    _id: "5f1ed1ab493c895c310de665",
    text: "When birds fall from the sky, a promise shall mark the end time of peace and life without hunger.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    _id: "5f1ed206493c895c310de666",
    text: "It shall be when echoes sound, the broken sword will cause peasants to take up arms and activate the rise of ancient magic.",
    model: "ItemBase",
    typeId: "Longsword",
  },
  {
    _id: "5f1ed20c493c895c310de667",
    text: "It shall be when echoes sound, the broken sword will cause peasants to take up arms and activate the rise of ancient magic.",
    model: "ItemBase",
    typeId: "Greatsword",
  },
  {
    _id: "5f1ed257493c895c310de668",
    text: "Once gloomy night, true love shall mark the age of life and an eternal night.",
    model: "ItemSlot",
    typeId: "misc",
  },
  {
    _id: "5f1ed271493c895c310de669",
    text: "The world turning to blood.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    _id: "5f1ed284493c895c310de66a",
    text: "Two brothers.",
    model: "ItemBase",
    typeId: "Ring",
  },
  {
    _id: "5f1ed29a493c895c310de66b",
    text: "When the carillons call, I will answer.",
    model: "ItemSlot",
    typeId: "gloves",
  },
  {
    _id: "5f1ed2b6493c895c310de66c",
    text: "Widowmaker.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    _id: "5f1ed2da493c895c310de66d",
    text: "This looks like it once belonged to an Elf.",
    model: "ItemSlot",
    typeId: "helmet",
  },
  {
    _id: "5f1ed2fa493c895c310de66e",
    text: "Slimy and covered in mold.",
    model: "ItemSlot",
    typeId: "helmet",
  },
  {
    _id: "5f1ed309493c895c310de66f",
    text: "Looks as if it has sat underwater for decades.",
    model: "ItemSlot",
    typeId: "helmet",
  },
  {
    _id: "5f1ed325493c895c310de670",
    text: "Bejeweled with gems, this helmet is a piece to behold.",
    model: "ItemSlot",
    typeId: "helmet",
  },
  {
    _id: "5f1ed33d493c895c310de671",
    text: "Two sharp horns extend from the front of this helmet.",
    model: "ItemSlot",
    typeId: "helmet",
  },
  {
    _id: "5f1ed370493c895c310de672",
    text: "This helmet has a muted red plume.",
    model: "ItemSlot",
    typeId: "helmet",
  },
  {
    _id: "5f1ed381493c895c310de673",
    text: "This helmet has a pale green plume.",
    model: "ItemSlot",
    typeId: "helmet",
  },
  {
    _id: "5f1ed3dc493c895c310de674",
    text: "Milk turn to glass, a crack opens in the great wall.",
    model: "ItemSlot",
    typeId: "body",
  },
  {
    _id: "5f1ed401493c895c310de675",
    text: "Fits a bit tight.",
    model: "ItemSlot",
    typeId: "body",
  },
  {
    _id: "5f1ed40a493c895c310de676",
    text: "Fits a bit loose.",
    model: "ItemSlot",
    typeId: "body",
  },
  {
    _id: "5f1ed443493c895c310de677",
    text: "Engraved with the sigil of Azuth.",
    model: "ItemSlot",
    typeId: "body",
  },
  {
    _id: "5f1ed44c493c895c310de678",
    text: "Engraved with the sigil of Tyr.",
    model: "ItemSlot",
    typeId: "body",
  },
  {
    _id: "5f1ed465493c895c310de679",
    text: "Engraved with the symbol of Kelemvor.",
    model: "ItemSlot",
    typeId: "body",
  },
  {
    _id: "5f1ed61d493c895c310de67a",
    text: "Clean and pristine, someone has been keeping this armour in great shape.",
    model: "ItemSlot",
    typeId: "body",
  },
  {
    _id: "5f1ed630493c895c310de67b",
    text: "Edges crusted with dried blood.",
    model: "ItemSlot",
    typeId: "body",
  },
  {
    _id: "5f1ed762493c895c310de67c",
    text: "Resources exist to be consumed.",
    model: "ItemSlot",
    typeId: "gloves",
  },
  {
    _id: "5f1ed77b493c895c310de67d",
    text: "Resources exist to be consumed.",
    model: "ItemSlot",
    typeId: "helmet",
  },
  {
    _id: "5f1ed782493c895c310de67e",
    text: "Resources exist to be consumed.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    _id: "5f1ed7be493c895c310de67f",
    text: '"Give a man a fish, and you can feed him for a day. But give a fish a man, and you can feed it for a month." - Song of the Sirens',
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    _id: "5f1ed898493c895c310de680",
    text: "They look like they might be waterproof, but so does everything until it gets wet.",
    model: "ItemSlot",
    typeId: "boots",
  },
  {
    _id: "5f1ed8ba493c895c310de681",
    text: "Stinky",
    model: "ItemSlot",
    typeId: "boots",
  },
  {
    _id: "5f1ed8cc493c895c310de682",
    text: "Still warm.",
    model: "ItemSlot",
    typeId: "boots",
  },
  {
    _id: "5f1ed91c493c895c310de683",
    text: "These boots were made a farmer, now they are the boots of war.",
    model: "ItemSlot",
    typeId: "boots",
  },
  {
    _id: "5f1ed93d493c895c310de684",
    text: "Size 10",
    model: "ItemSlot",
    typeId: "boots",
  },
  {
    _id: "5f1ed945493c895c310de685",
    text: "Size 11",
    model: "ItemSlot",
    typeId: "boots",
  },
  {
    _id: "5f1ed968493c895c310de686",
    text: "They look as if they have never been worn.",
    model: "ItemSlot",
    typeId: "boots",
  },
  {
    _id: "5f1ed979493c895c310de687",
    text: "Two lefts.",
    model: "ItemSlot",
    typeId: "boots",
  },
  {
    _id: "5f1ed9a3493c895c310de688",
    text: "Dyed black.",
    model: "ItemSlot",
    typeId: "boots",
  },
  {
    _id: "5f1ed9bf493c895c310de689",
    text: "Embossed with a depiction of a mountain.",
    model: "ItemSlot",
    typeId: "boots",
  },
  {
    _id: "5f1ed9c8493c895c310de68a",
    text: "Embossed with a depiction of a tree.",
    model: "ItemSlot",
    typeId: "boots",
  },
  {
    _id: "5f1ed9db493c895c310de68b",
    text: "The laces are missing.",
    model: "ItemSlot",
    typeId: "boots",
  },
  {
    _id: "5f1eda29493c895c310de68c",
    text: "What was thought to be lost to time returns at last.",
    model: "ItemSlot",
    typeId: "jewelry",
  },
  {
    _id: "5f1eda67493c895c310de68d",
    text: "One must stoop to aid one's fallen brother.",
    model: "ItemSlot",
    typeId: "jewelry",
  },
  {
    _id: "5f1eda7b493c895c310de68e",
    text: "Justice to the right, mercy to the left.",
    model: "ItemSlot",
    typeId: "jewelry",
  },
  {
    _id: "5f1edb6a493c895c310de68f",
    text: '"There is a fine line between consideration and hesitation. The former is wisdom, the latter is fear." - Izaro',
    model: "ItemSlot",
    typeId: "jewelry",
  },
  {
    _id: "5f1edba3493c895c310de690",
    text: "Easy to anger, easy to love.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    _id: "5f1edbaf493c895c310de691",
    text: "Simple and effective.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    _id: "5f1edbe1493c895c310de692",
    text: "A very short, wide, jagged blade made of crystal is held by a grip wrapped in high quality, red snake leather.",
    model: "ItemBase",
    typeId: "Dagger",
  },
  {
    _id: "5f1edc13493c895c310de693",
    text: "The blade has a narrow, straight cross-guard, offering plenty of protection to the owner's hands.",
    model: "ItemBase",
    typeId: "Longsword",
  },
  {
    _id: "5f1edc19493c895c310de694",
    text: "The blade has a narrow, straight cross-guard, offering plenty of protection to the owner's hands.",
    model: "ItemBase",
    typeId: "Greatsword",
  },
  {
    _id: "5f1edc51493c895c310de695",
    text: "A fairly small  rare gem is inlaid into the weapon, fine details which prove how carefully this weapon was crafted.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    _id: "5f1edc85493c895c310de696",
    text: "Intricate decorational patterns have been carefully etched into the metal, which is supposed to contain a hidden power.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    _id: "5f1ef34c493c895c310de697",
    text: "A long, slim, straight blade made of silver is held by a grip wrapped in leather of unknown origin.",
    model: "ItemBase",
    typeId: "Rapier",
  },
  {
    _id: "5f1ef357493c895c310de698",
    text: "A long, slim, straight blade made of silver is held by a grip wrapped in leather of unknown origin.",
    model: "ItemBase",
    typeId: "Longsword",
  },
  {
    _id: "5f1ef379493c895c310de699",
    text: "A long, slim, curved blade made of silver is held by a grip wrapped in leather of unknown origin.",
    model: "ItemBase",
    typeId: "Sickle",
  },
  {
    _id: "5f1ef3cd493c895c310de69a",
    text: "The chips and bends of this weapon only serve to better tear the flesh from anyone or anything you strike.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    _id: "5f1ef3df493c895c310de69b",
    text: "This weapon is used by anybody with a decent amount of money. A great weapon for proven fighters.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    _id: "5f1ef412493c895c310de69c",
    text: "The cross-guard has a gilded tooth on each side, the cost of this weapon must have been high.",
    model: "ItemBase",
    typeId: "Longsword",
  },
  {
    _id: "5f1ef418493c895c310de69d",
    text: "The cross-guard has a gilded tooth on each side, the cost of this weapon must have been high.",
    model: "ItemBase",
    typeId: "Greatsword",
  },
  {
    _id: "5f1ef423493c895c310de69e",
    text: "The cross-guard has a gilded tooth on each side, the cost of this weapon must have been high.",
    model: "ItemBase",
    typeId: "Dagger",
  },
  {
    _id: "5f1ef436493c895c310de69f",
    text: "The cross-guard has a gilded tooth on each side, the cost of this weapon must have been high.",
    model: "ItemBase",
    typeId: "Scimitar",
  },
  {
    _id: "5f1ef441493c895c310de6a0",
    text: "One sharp edge makes this weapon ideal for both blocking and slicing, your enemies won't stand a chance.",
    model: "ItemBase",
    typeId: "Scimitar",
  },
  {
    _id: "5f1ef49f493c895c310de6a1",
    text: "A line of text is engraved on the blade which seems to glow faintly in the night.",
    model: "ItemBase",
    typeId: "Longsword",
  },
  {
    _id: "5f1ef4a6493c895c310de6a2",
    text: "A line of text is engraved on the blade which seems to glow faintly in the night.",
    model: "ItemBase",
    typeId: "Greatsword",
  },
  {
    _id: "5f1ef4b0493c895c310de6a3",
    text: "A line of text is engraved on the blade which seems to glow faintly in the night.",
    model: "ItemBase",
    typeId: "Axe",
  },
  {
    _id: "5f1ef4b8493c895c310de6a4",
    text: "A line of text is engraved on the blade which seems to glow faintly in the night.",
    model: "ItemBase",
    typeId: "Dagger",
  },
  {
    _id: "5f1ef4c7493c895c310de6a5",
    text: "A line of text is engraved on the blade which seems to glow faintly in the night.",
    model: "ItemBase",
    typeId: "Sickle",
  },
  {
    _id: "5f1ef4eb493c895c310de6a6",
    text: "A line of text is engraved along the edge of the blade which seems to glow faintly in the night.",
    model: "ItemBase",
    typeId: "Battleaxe",
  },
  {
    _id: "5f1ef4f8493c895c310de6a7",
    text: "A line of text is engraved on the blade which seems to glow faintly in the night.",
    model: "ItemBase",
    typeId: "Glaive",
  },
  {
    _id: "5f1ef501493c895c310de6a8",
    text: "A line of text is engraved on the blade which seems to glow faintly in the night.",
    model: "ItemBase",
    typeId: "Greataxe",
  },
  {
    _id: "5f1ef528493c895c310de6a9",
    text: "Text is engraved on the head of the hammer which seems to glow faintly in the night.",
    model: "ItemBase",
    typeId: "Warhammer",
  },
  {
    _id: "5f1ef56a493c895c310de6aa",
    text: "The material of this weapon is translucent like glass, yet does not break.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    _id: "5f1ef5cd493c895c310de6ab",
    text: "Covered in spikes, any wrong move could result in disaster, but for whom.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    _id: "5f1ef5ee493c895c310de6ac",
    text: "This weapon is used by the royal guard. An excellent weapon for the defense of the country.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    _id: "5f1ef64b493c895c310de6ad",
    text: "The weapon itself is fairly simple. No decorations or engraved patterns, it needs no decorations, it only needs to be strong and dangerous.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    _id: "5f1ef661493c895c310de6ae",
    text: "This weapon is used by just about anybody. Whatever the purpose of its owner, this weapon will be sufficient.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    _id: "5f1ef68f493c895c310de6af",
    text: "The weapon itself is unadorned. No decorations of any sorts are on it, but it will surely be decorated in battle.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    _id: "5f1ef7a6493c895c310de6b0",
    text: "This weapon was clearly a custom order, probably by an important figure.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    _id: "5f1ef7be493c895c310de6b1",
    text: "Gilded accents adorn this weapon.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    _id: "5f1ef7ec493c895c310de6b2",
    text: "Emerald green spring vines have intertwined themselves with this weapon.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    _id: "5f1ef800493c895c310de6b3",
    text: "This weapon is freezing to the touch.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    _id: "5f1ef854493c895c310de6b4",
    text: "Unintelligible whispers can be heard from this weapon, only in the quietest of moments.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    _id: "5f1ef881493c895c310de6b5",
    text: "This flask looks to be carved from a single large gem stone.",
    model: "ItemBase",
    typeId: "Flask",
  },
  {
    _id: "5f1ef8b4493c895c310de6b6",
    text: "The beautiful crystalline structure reflects light in the most mesmerizing of ways.",
    model: "ItemBase",
    typeId: "Flask",
  },
  {
    _id: "5f1ef8d2493c895c310de6b7",
    text: "The beautiful crystalline structure of the inlaid gems reflects light in the most mesmerizing of ways.",
    model: "ItemBase",
    typeId: "Ring",
  },
  {
    _id: "5f1ef961493c895c310de6b8",
    text: "A mystical eye is carved into the flat of the weapon, it has been said that one can lose themselves within the ocean of its eye.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    _id: "5f20678c69172e05524a5b3e",
    text: "This hood shrouds the face in darkness.",
    model: "ItemBase",
    typeId: "Silk Hood",
  },
  {
    _id: "5f2067bf69172e05524a5b3f",
    text: "Retains the scent of a campfire.",
    model: "ItemSlot",
    typeId: "helmet",
  },
  {
    _id: "5f20681369172e05524a5b40",
    text: "Attached to the top is a wolf's head, its body is used as a cloak.",
    model: "ItemSlot",
    typeId: "helmet",
  },
  {
    _id: "5f20683469172e05524a5b41",
    text: "Mounted to the top of the helmet is a dead raven.",
    model: "ItemBase",
    typeId: "Plate Helmet",
  },
  {
    _id: "5f20685869172e05524a5b42",
    text: "The fabric seems to change colors in the moonlight.",
    model: "ItemBase",
    typeId: "Silk Hood",
  },
  {
    _id: "5f20686569172e05524a5b43",
    text: "The fabric seems to change colors in the moonlight.",
    model: "ItemBase",
    typeId: "Silk Robes",
  },
  {
    _id: "5f20688769172e05524a5b44",
    text: "A flap folds down to cover most of the face.",
    model: "ItemSlot",
    typeId: "helmet",
  },
  {
    _id: "5f2068a469172e05524a5b45",
    text: "The breastplate is made from several layers of leather, which perfectly sit just under the shoulders. It covers almost everything from the neck down, it narrows near the groin and leaves part the sides exposed.",
    model: "ItemBase",
    typeId: "Leather Armour",
  },
  {
    _id: "5f20697669172e05524a5b46",
    text: "Brass with dark tinted lenses.",
    model: "ItemBase",
    typeId: "Goggles",
  },
  {
    _id: "5f2069c069172e05524a5b47",
    text: "Polished silver with faceted gems for lenses, these googles almost give their wearer compound vision.",
    model: "ItemBase",
    typeId: "Goggles",
  },
  {
    _id: "5f2069fa69172e05524a5b48",
    text: "Leather straps hold two keen birds eye shaped lenses snug against the face.",
    model: "ItemBase",
    typeId: "Goggles",
  },
  {
    _id: "5f206a5b69172e05524a5b49",
    text: "One large round lens made of glass covers the face. It is surrounded by heavy riveted steel and some type of rubber, it looks to give a waterproof seal.",
    model: "ItemBase",
    typeId: "Goggles",
  },
  {
    _id: "5f206a9a69172e05524a5b4a",
    text: "stylish leather and gold hold two mirrored lenses. ",
    model: "ItemBase",
    typeId: "Goggles",
  },
  {
    _id: "5f206af069172e05524a5b4b",
    text: "Green bubbling liquid rolls back and forth within the flask. Small bones rattle against the bottom.",
    model: "ItemBase",
    typeId: "Flask",
  },
  {
    _id: "5f206ba369172e05524a5b4c",
    text: "This flask contains a milky white liquid with the consistency of gelatin. It is warm to the touch.",
    model: "ItemBase",
    typeId: "Flask",
  },
  {
    _id: "5f206c0169172e05524a5b4d",
    text: "A ruby red smoke fills this flask. It forever swirls around as if it was a storm cloud.",
    model: "ItemBase",
    typeId: "Flask",
  },
  {
    _id: "5f206c2369172e05524a5b4e",
    text: "Leather wrapped and double corked, this flask is ready for travel.",
    model: "ItemBase",
    typeId: "Flask",
  },
  {
    _id: "5f206c6d69172e05524a5b4f",
    text: "A decorated golden cask with a chain. Much too expensive for a common farmer",
    model: "ItemBase",
    typeId: "Flask",
  },
  {
    _id: "5f206c7d69172e05524a5b50",
    text: "A simple goat bladder.",
    model: "ItemBase",
    typeId: "Flask",
  },
  {
    _id: "5f206c9d69172e05524a5b51",
    text: "A simple glass bottle. Functional and affordable.",
    model: "ItemBase",
    typeId: "Flask",
  },
  {
    _id: "5f206cc669172e05524a5b52",
    text: "This sturdy rounded afro shield, made from iron, offers a robust cover.",
    model: "ItemBase",
    typeId: "Shield",
  },
  {
    _id: "5f206cea69172e05524a5b53",
    text: "A true work of mastery, this shield was forged by elves in an ancient workshop.",
    model: "ItemBase",
    typeId: "Shield",
  },
  {
    _id: "5f206d2569172e05524a5b54",
    text: "The shield's edges are embellished with broad metal lining and have been adorned with raven feathers.",
    model: "ItemBase",
    typeId: "Shield",
  },
  {
    _id: "5f206d4369172e05524a5b55",
    text: "The shields center is garnished with a large gem and seemingly magical runes encircle its edges.",
    model: "ItemBase",
    typeId: "Shield",
  },
  {
    _id: "5f206d8669172e05524a5b56",
    text: "Scars and cuts give this shield a long history of adventure.",
    model: "ItemBase",
    typeId: "Shield",
  },
  {
    _id: "5f206dd369172e05524a5b57",
    text: "This large, rough, wooden oval shield, offers basic protection.",
    model: "ItemBase",
    typeId: "Shield",
  },
  {
    _id: "5f206de569172e05524a5b58",
    text: "The shield's edges are embellished with double rows of metal studs and have been decorated with small repeated symbols.",
    model: "ItemBase",
    typeId: "Shield",
  },
  {
    _id: "5f206e1f69172e05524a5b59",
    text: "This shield is the result of expertise, it was forged by titan orcs at the heart of a volcano.",
    model: "ItemBase",
    typeId: "Shield",
  },
  {
    _id: "5f206e4969172e05524a5b5a",
    text: "This impressive triangular kite shield, made from hardwood and lined with bronze, offers reinforced protection.",
    model: "ItemBase",
    typeId: "Shield",
  },
  {
    _id: "5f206e7f69172e05524a5b5b",
    text: "It's clear this shield hasn't heard the cry of battle. Nothing has left its mark yet.",
    model: "ItemBase",
    typeId: "Shield",
  },
  {
    _id: "5f206ea769172e05524a5b5c",
    text: "The shield's edges are augmented with large spikes and have been decorated with vibrant paintwork.",
    model: "ItemBase",
    typeId: "Shield",
  },
  {
    _id: "5f206f1f69172e05524a5b5d",
    text: "This huge oval shield is made from blackened hardwood. It stands from head to foot and has a transparent crystal slotted at eye level.",
    model: "ItemBase",
    typeId: "Shield",
  },
  {
    _id: "5f206f8169172e05524a5b5e",
    text: "The inside of this shield has numbers etched in blood. One could only assume what they were counting.",
    model: "ItemBase",
    typeId: "Shield",
  },
  {
    _id: "5f206fd769172e05524a5b5f",
    text: "Raven black wood tipped with red feathers.",
    model: "ItemBase",
    typeId: "Arrows (20)",
  },
  {
    _id: "5f20700f69172e05524a5b60",
    text: "Snow white wood tipped with brightly colored feathers. ",
    model: "ItemBase",
    typeId: "Arrows (20)",
  },
  {
    _id: "5f20704169172e05524a5b61",
    text: "These arrows have a broad glass tip, unique, but not very effective against modern armour.",
    model: "ItemBase",
    typeId: "Arrows (20)",
  },
  {
    _id: "5f20706669172e05524a5b62",
    text: "Common arrows used by everyone from militia to farmers.",
    model: "ItemBase",
    typeId: "Arrows (20)",
  },
  {
    _id: "5f20707a69172e05524a5b63",
    text: "These arrows have a barbed tip.",
    model: "ItemBase",
    typeId: "Arrows (20)",
  },
  {
    _id: "5f2070a869172e05524a5b64",
    text: "These arrows are made from knotted cracking wood yet they look to still function.",
    model: "ItemBase",
    typeId: "Arrows (20)",
  },
  {
    _id: "5f2096f069172e05524a5b6d",
    text: '"Stand behind me"',
    model: "ItemBase",
    typeId: "Shield",
  },
  {
    _id: "5f20994569172e05524a5b6f",
    text: "This round silver shield has been polished to a mirrored surface.",
    model: "ItemBase",
    typeId: "Shield",
  },
  {
    _id: "5f26d4563d68df03ebb7fe5c",
    text: "I could tell you but then I would have to kill you.",
    model: "ItemSlot",
    typeId: "jewelry",
  },
  {
    _id: "5f5fa2554260360d2808c882",
    text: "The string looks like it has been recently replaced.",
    model: "ItemBase",
    typeId: "Shortbow",
  },
  {
    _id: "5f5fa2604260360d2808c883",
    text: "The string looks like it has been recently replaced.",
    model: "ItemBase",
    typeId: "Crossbow",
  },
  {
    _id: "5f5fa26a4260360d2808c884",
    text: "The string looks like it has been recently replaced.",
    model: "ItemBase",
    typeId: "Longbow",
  },
  {
    _id: "5f5fa2a34260360d2808c885",
    text: "The string is fraying near the ends, it looks as if it might snap with every draw.",
    model: "ItemBase",
    typeId: "Shortbow",
  },
  {
    _id: "5f5fa2ab4260360d2808c886",
    text: "The string is fraying near the ends, it looks as if it might snap with every draw.",
    model: "ItemBase",
    typeId: "Crossbow",
  },
  {
    _id: "5f5fa2b44260360d2808c887",
    text: "The string is fraying near the ends, it looks as if it might snap with every draw.",
    model: "ItemBase",
    typeId: "Longbow",
  },
  {
    _id: "5f6225c479c7000d931539e8",
    text: "Forged in part with metals from a meteorite long forgotten.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    _id: "5f6225c979c7000d931539e9",
    text: "Forged in part with metals from a meteorite long forgotten.",
    model: "ItemSlot",
    typeId: "helmet",
  },
  {
    _id: "5f6225cf79c7000d931539ea",
    text: "Forged in part with metals from a meteorite long forgotten.",
    model: "ItemSlot",
    typeId: "body",
  },
  {
    _id: "5f6225d579c7000d931539eb",
    text: "Forged in part with metals from a meteorite long forgotten.",
    model: "ItemSlot",
    typeId: "jewelry",
  },
  {
    _id: "5f63abd879c7000d931539ef",
    text: "This helmet is adorned with golden wings on either side.",
    model: "ItemSlot",
    typeId: "helmet",
  },
  {
    _id: "5f63b33279c7000d931539f8",
    text: "These boots are lined with a strangely light meshed material with a soft but stiff black material as its sole. They leave behind a faint, quickly dissipating mist where they step.",
    model: "ItemSlot",
    typeId: "boots",
  },
  {
    _id: "5f63b3d179c7000d931539f9",
    text: "If you hesitate, you die.",
    model: "ItemSlot",
    typeId: "boots",
  },
  {
    _id: "5f63b77c79c7000d931539fc",
    text: "A crescent shaped scar tears through the middle of the shield, a dark mark which adorns the surface.",
    model: "ItemBase",
    typeId: "Shield",
  },
  {
    _id: "5f63b9b079c7000d931539ff",
    text: "A flat black shield that feels cool to the touch. It seems to absorb the light around it.",
    model: "ItemBase",
    typeId: "Shield",
  },
  {
    _id: "5f63d7f379c7000d93153a00",
    text: "This shield has been fashioned out of the skull of some enormous beast. The sockets where eyes once sat are eerily shrouded by darkness.",
    model: "ItemBase",
    typeId: "Shield",
  },
  {
    _id: "5f73a22a79c7000d93153a28",
    text: "All or nothing...",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    _id: "5f73a3e279c7000d93153a2b",
    text: "This ring is made of silver and mother of pearl.",
    model: "ItemBase",
    typeId: "Ring",
  },
  {
    _id: "5f73a42979c7000d93153a2c",
    text: "This ring is made of dark metal laced with veins of gold.",
    model: "ItemBase",
    typeId: "Ring",
  },
  {
    _id: "5f73a43079c7000d93153a2d",
    text: "This ring is made of dark metal laced with veins of red.",
    model: "ItemBase",
    typeId: "Ring",
  },
  {
    _id: "5f73a43879c7000d93153a2e",
    text: "This ring is made of dark metal laced with veins of blue.",
    model: "ItemBase",
    typeId: "Ring",
  },
  {
    _id: "5f73a44279c7000d93153a2f",
    text: "This ring is made of dark metal laced with veins of emerald.",
    model: "ItemBase",
    typeId: "Ring",
  },
  {
    _id: "5f73a59d79c7000d93153a32",
    text: "This fine arrow of cedar wood and kingfisher feathers is tipped with a sharp hydra’s tooth.",
    model: "ItemBase",
    typeId: "Arrows (20)",
  },
  {
    _id: "5f73a64a79c7000d93153a34",
    text: "You can't be sure... but it might just be whiskey.",
    model: "ItemBase",
    typeId: "Flask",
  },
  {
    _id: "5f79bee972aea558c42ebab6",
    text: "This weapons is made with icy grey steel and wrapped with blue stained leather.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    _id: "5f79bf0f72aea558c42ebab7",
    text: "The eye of some creature is floating in the liquid.",
    model: "ItemBase",
    typeId: "Flask",
  },
  {
    _id: "5f79bf3572aea558c42ebab8",
    text: "The liquid inside is almost too thick to pour.",
    model: "ItemBase",
    typeId: "Flask",
  },
  {
    _id: "5f79bfa372aea558c42ebab9",
    text: "This weapon was carved from ancient gnarled oak limbs. They twist and pull in unnatural directions.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    _id: "5f79c02c72aea558c42ebaba",
    text: "A mixture of liquids and powders that shimmers in the light. Do not mix with alcohol.",
    model: "ItemBase",
    typeId: "Flask",
  },
  {
    _id: "5f79c44172aea558c42ebabd",
    text: "Ribbons adorn this weapon and flow elegantly at the slightest breath of wind.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    _id: "5f79c45872aea558c42ebabe",
    text: "Ribbons adorn this armour and flow elegantly at the slightest breath of wind.",
    model: "ItemSlot",
    typeId: "body",
  },
  {
    _id: "5f7a339a72aea558c42ebabf",
    text: "The decoration on the weapon depicts a gruesome disembowelment that seems to writhe grotesquely out of the corner of your eye.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    _id: "5f7b799a72aea558c42ebaed",
    text: "Mismatched panels of this armour are held together with twine. It looks like it has been cobbled together from a few different sets.",
    model: "ItemSlot",
    typeId: "body",
  },
  {
    _id: "5f7cbd4b72aea558c42ebaff",
    text: "This ring is adorned with gilded rat skulls.",
    model: "ItemBase",
    typeId: "Ring",
  },
  {
    _id: "5f7cbdb472aea558c42ebb00",
    text: "This brass ring is a pointed ovoid. It is accented with a small opaque turquoise cushion-cut gem surrounded by luminescent dust.",
    model: "ItemBase",
    typeId: "Ring",
  },
  {
    _id: "5f7cbdc072aea558c42ebb01",
    text: "A simple steel ring.",
    model: "ItemBase",
    typeId: "Ring",
  },
  {
    _id: "5f7cbdeb72aea558c42ebb02",
    text: "This deep black rough cut ring is warm to the touch.",
    model: "ItemBase",
    typeId: "Ring",
  },
  {
    _id: "5f7cbe1772aea558c42ebb03",
    text: "This gold amulet is set with small iridescent orange and green pear-cut gems.",
    model: "ItemBase",
    typeId: "Amulet",
  },
  {
    _id: "5f7cbe3e72aea558c42ebb04",
    text: "This amulet is nothing more then a rock tied with string, still you can feel it has power.",
    model: "ItemBase",
    typeId: "Amulet",
  },
  {
    _id: "5f7cbe5672aea558c42ebb05",
    text: "This silver pendant is shaped like a deer.",
    model: "ItemBase",
    typeId: "Amulet",
  },
  {
    _id: "5f7cbe8972aea558c42ebb06",
    text: "This steel pendant is shaped like a wolf's head. It's eyes faintly glow red.",
    model: "ItemBase",
    typeId: "Amulet",
  },
  {
    _id: "5f7cbea772aea558c42ebb07",
    text: "This silver ring is set with a large black stone.",
    model: "ItemBase",
    typeId: "Ring",
  },
  {
    _id: "5f7cbef572aea558c42ebb08",
    text: "This necklace is tied with thin leather strips. it is engraved with an image of a dove.",
    model: "ItemBase",
    typeId: "Amulet",
  },
  {
    _id: "5f7cbf2a72aea558c42ebb09",
    text: "This small simple leather necklace has a single glass ornament in the shape of a water droplet.",
    model: "ItemBase",
    typeId: "Amulet",
  },
  {
    _id: "5f7cbf5c72aea558c42ebb0a",
    text: "Black leather bands suspend a polished ruby red gemstone.",
    model: "ItemBase",
    typeId: "Amulet",
  },
  {
    _id: "5f7cbf8d72aea558c42ebb0b",
    text: "Fine gold chain with a large pendant engraved with the image of a cat.",
    model: "ItemBase",
    typeId: "Amulet",
  },
  {
    _id: "5f7cbfad72aea558c42ebb0c",
    text: "Long black chains woven to resemble to feathers of a raven.",
    model: "ItemBase",
    typeId: "Amulet",
  },
  {
    _id: "5f7cbfc372aea558c42ebb0d",
    text: "Long golden chains woven to resemble the wings of an eagle.",
    model: "ItemBase",
    typeId: "Amulet",
  },
  {
    _id: "5f7cbfe872aea558c42ebb0e",
    text: "A white egg shaped opal hangs from thick gold chains.",
    model: "ItemBase",
    typeId: "Amulet",
  },
  {
    _id: "5f7cbffb72aea558c42ebb0f",
    text: "A simple, robust gold chain.",
    model: "ItemBase",
    typeId: "Amulet",
  },
  {
    _id: "5f7cc00472aea558c42ebb10",
    text: "A simple, robust silver chain.",
    model: "ItemBase",
    typeId: "Amulet",
  },
  {
    _id: "5f7cc03472aea558c42ebb11",
    text: "This gold pendant is bell-shaped.",
    model: "ItemBase",
    typeId: "Amulet",
  },
  {
    _id: "5f7cc0cb72aea558c42ebb12",
    text: "This amulet is sewn from pale turquoise leather embossed with ocean waves.",
    model: "ItemBase",
    typeId: "Amulet",
  },
  {
    _id: "5f7cc13872aea558c42ebb13",
    text: "This iridescent goo is dark purple in color.  It is odorless.",
    model: "ItemBase",
    typeId: "Flask",
  },
  {
    _id: "5f7cc14572aea558c42ebb14",
    text: "This transparent slime is magenta in color.  It smells like cheddar cheese and ink.",
    model: "ItemBase",
    typeId: "Flask",
  },
  {
    _id: "5f7cc16772aea558c42ebb15",
    text: "This coarse liquid is magenta in color.  It smells like burned coffee.",
    model: "ItemBase",
    typeId: "Flask",
  },
  {
    _id: "5f7cc19472aea558c42ebb16",
    text: "The liquid is clear but it smells of death.",
    model: "ItemBase",
    typeId: "Flask",
  },
  {
    _id: "5f7cc1b572aea558c42ebb17",
    text: "This cylindrical bottle is made of transparent bright orange glass.  It has a mid-length neck, stands about three inches tall, and most of its label has been torn off.",
    model: "ItemBase",
    typeId: "Flask",
  },
  {
    _id: "5f7cc1ca72aea558c42ebb18",
    text: "This rectangular bottle is made of translucent smokey rose glass.",
    model: "ItemBase",
    typeId: "Flask",
  },
  {
    _id: "5f7cc20072aea558c42ebb19",
    text: "This pyramid-shaped bottle is made of opaque bright blue glass.  It has a long neck, and a colorful label.",
    model: "ItemBase",
    typeId: "Flask",
  },
  {
    _id: "5f7cc26672aea558c42ebb1a",
    text: "This belt is made from woven black leather.",
    model: "ItemBase",
    typeId: "Belt",
  },
  {
    _id: "5f7cc27072aea558c42ebb1b",
    text: "This belt is made from woven brown leather.",
    model: "ItemBase",
    typeId: "Belt",
  },
  {
    _id: "5f7cc28072aea558c42ebb1c",
    text: "This belt is made from woven bleached leather.",
    model: "ItemBase",
    typeId: "Belt",
  },
  {
    _id: "5f7cc29d72aea558c42ebb1d",
    text: "This thin belt has a delicate silver buckle.",
    model: "ItemBase",
    typeId: "Belt",
  },
  {
    _id: "5f7cc2c472aea558c42ebb1e",
    text: "A thick belt made from maroon leather and clasped with a large steel buckle.",
    model: "ItemBase",
    typeId: "Belt",
  },
  {
    _id: "5f7cc3b472aea558c42ebb1f",
    text: "Made of thick chains this belt will not break easily.",
    model: "ItemBase",
    typeId: "Belt",
  },
  {
    _id: "60ef8f05009f151f2379dc50",
    text: "Adorned with ornate white molded inlays.",
    model: "ItemSlot",
    typeId: "gloves",
  },
  {
    _id: "60ef8f46009f151f2379dc51",
    text: "Decorated with tiny blue gemstones.",
    model: "ItemSlot",
    typeId: "gloves",
  },
  {
    _id: "60ef8f75009f151f2379dc52",
    text: "The material is laced with a foreign substance that glitters in the light of a full moon.",
    model: "ItemSlot",
    typeId: "gloves",
  },
  {
    _id: "60ef8fab009f151f2379dc53",
    text: "Tiny slivers of moonlight shine out of cracks in the palm of the glove.",
    model: "ItemSlot",
    typeId: "gloves",
  },
  {
    _id: "60ef8fe4009f151f2379dc54",
    text: "Wide jagged scars stretch across the back of the gloves.",
    model: "ItemSlot",
    typeId: "gloves",
  },
  {
    _id: "60ef9096009f151f2379dc55",
    text: "These gloves have an ugly, pockmarked surface that reminds one of Seth and disease.",
    model: "ItemSlot",
    typeId: "gloves",
  },
  {
    _id: "60ef9149009f151f2379dc56",
    text: "The palms of the gloves are coated with rubber, giving them extraordinary grip.",
    model: "ItemSlot",
    typeId: "gloves",
  },
  {
    _id: "60ef9185009f151f2379dc57",
    text: "Thick and warm, these gloves are lined with something soft.",
    model: "ItemSlot",
    typeId: "gloves",
  },
  {
    _id: "60ef91d7009f151f2379dc58",
    text: "Extra protection around the wrists and knuckles makes these gloves great for tough jobs.",
    model: "ItemSlot",
    typeId: "gloves",
  },
  {
    _id: "60ef927b009f151f2379dc59",
    text: "Decorated with crimson feathers.",
    model: "ItemSlot",
    typeId: "gloves",
  },
  {
    _id: "60ef931b009f151f2379dc5a",
    text: "Undecorated, unassuming gloves for the simple adventurer.",
    model: "ItemSlot",
    typeId: "gloves",
  },
  {
    _id: "60ef935e009f151f2379dc5b",
    text: "Weatherproof, waterproof and witch proof... or maybe just witch resistant.",
    model: "ItemSlot",
    typeId: "gloves",
  },
  {
    _id: "60ef9393009f151f2379dc5c",
    text: "Extra long wrist guards stretch past the usual reach of these gloves.",
    model: "ItemSlot",
    typeId: "gloves",
  },
  {
    _id: "60ef9497009f151f2379dc5d",
    text: "Silvered and polished, you can see your reflection in these gloves.",
    model: "ItemBase",
    typeId: "Plate Gloves",
  },
  {
    _id: "60ef9512009f151f2379dc5e",
    text: "Ruby red gemstones sparkle at the tip of each finger and grab the attention of any onlookers.",
    model: "ItemSlot",
    typeId: "gloves",
  },
  {
    _id: "60ef954e009f151f2379dc5f",
    text: "One finger is embossed with a small flower.",
    model: "ItemSlot",
    typeId: "gloves",
  },
  {
    _id: "60ef958a009f151f2379dc60",
    text: "The back of the glove is painted white but it has began to flake away.",
    model: "ItemSlot",
    typeId: "gloves",
  },
  {
    _id: "60ef95b2009f151f2379dc61",
    text: "One finger has been engraved with a symbol of a man under a tree.",
    model: "ItemSlot",
    typeId: "gloves",
  },
  {
    _id: "60ef95ca009f151f2379dc62",
    text: "The gloves are engraved with the symbol of a snake.",
    model: "ItemSlot",
    typeId: "gloves",
  },
  {
    _id: "60ef95e3009f151f2379dc63",
    text: "The gloves are engraved with the symbol of a blazing sun.",
    model: "ItemSlot",
    typeId: "gloves",
  },
  {
    _id: "60ef960e009f151f2379dc64",
    text: "The gloves feel light, almost weightless on your hands.",
    model: "ItemSlot",
    typeId: "gloves",
  },
  {
    _id: "60ef96b6009f151f2379dc65",
    text: "Durable, dark brown leather with multiple wrist clasps.",
    model: "ItemBase",
    typeId: "Leather Gloves",
  },
  {
    _id: "60f1835d009f151f2379dc68",
    text: "Thick rubber treads give these boots incredible grip even in muddy situations.",
    model: "ItemSlot",
    typeId: "boots",
  },
  {
    _id: "60f1839a009f151f2379dc69",
    text: "Polished clean, you can see your reflection in these boots.",
    model: "ItemBase",
    typeId: "Plate Boots",
  },
  {
    _id: "60f183ce009f151f2379dc6a",
    text: "Worn in just enough to make them comfortable but not enough to begin showing wear or age.",
    model: "ItemSlot",
    typeId: "boots",
  },
  {
    _id: "60f183fe009f151f2379dc6b",
    text: "A little bit tight, you hope these boots won't blister but you somehow doubt it.",
    model: "ItemSlot",
    typeId: "boots",
  },
  {
    _id: "60f1841a009f151f2379dc6c",
    text: "Dyed a moss green",
    model: "ItemSlot",
    typeId: "boots",
  },
  {
    _id: "60f18425009f151f2379dc6d",
    text: "Dyed a crimson red.",
    model: "ItemSlot",
    typeId: "boots",
  },
  {
    _id: "60f18456009f151f2379dc6e",
    text: "A small metal stud has been fasted to the heel of the boot. Perhaps as a makeshift stirrup.",
    model: "ItemSlot",
    typeId: "boots",
  },
  {
    _id: "60f18479009f151f2379dc6f",
    text: "A small metal stud has been hastily fastened to the toe of the boot.",
    model: "ItemSlot",
    typeId: "boots",
  },
  {
    _id: "60f184bc009f151f2379dc70",
    text: "Thin gold wire decorates the rim of the boots, almost too thin to see unless the light hits them a certain way.",
    model: "ItemSlot",
    typeId: "boots",
  },
  {
    _id: "60f1850a009f151f2379dc71",
    text: "You can't see any holes but that doesn't mean there aren't any there.",
    model: "ItemSlot",
    typeId: "boots",
  },
  {
    _id: "60f1852c009f151f2379dc72",
    text: "Extra wide boots, certainly custom made.",
    model: "ItemSlot",
    typeId: "boots",
  },
  {
    _id: "60f18545009f151f2379dc73",
    text: "Boots blackened with ash.",
    model: "ItemSlot",
    typeId: "boots",
  },
  {
    _id: "60f18577009f151f2379dc74",
    text: "The shield has a rich moss surface growing on its face.",
    model: "ItemBase",
    typeId: "Shield",
  },
  {
    _id: "60f18595009f151f2379dc75",
    text: "The armour has been blacked by ash or fire.",
    model: "ItemSlot",
    typeId: "body",
  },
  {
    _id: "60f185c6009f151f2379dc76",
    text: "Thick moss grows on the shoulders of this armour seemingly requiring no sunlight or even moisture.",
    model: "ItemSlot",
    typeId: "body",
  },
  {
    _id: "60f185e1009f151f2379dc77",
    text: "Blackened by ash or fire.",
    model: "ItemSlot",
    typeId: "gloves",
  },
  {
    _id: "60f1863b009f151f2379dc78",
    text: "Thin gold accents make this armour look better than it is.",
    model: "ItemSlot",
    typeId: "body",
  },
  {
    _id: "60f18667009f151f2379dc79",
    text: "The armour is laced with flecks of some unknown material that glows brightly under the light of a full moon.",
    model: "ItemSlot",
    typeId: "body",
  },
  {
    _id: "60f18822009f151f2379dc7a",
    text: "Fur lines these boots and keeps them warm even on the coldest nights.",
    model: "ItemSlot",
    typeId: "boots",
  },
  {
    _id: "60f1884c009f151f2379dc7b",
    text: "Gold horns are attached to the helmet.",
    model: "ItemSlot",
    typeId: "helmet",
  },
  {
    _id: "60f18858009f151f2379dc7c",
    text: "Goat horns are attached to the helmet.",
    model: "ItemSlot",
    typeId: "helmet",
  },
  {
    _id: "60f18876009f151f2379dc7d",
    text: "Shallow cuts mar the surface of the helmet.",
    model: "ItemSlot",
    typeId: "helmet",
  },
  {
    _id: "60f1888a009f151f2379dc7e",
    text: "Green vines encircle the helmet.",
    model: "ItemSlot",
    typeId: "helmet",
  },
  {
    _id: "60f188a9009f151f2379dc7f",
    text: "The helmet has been painted off white.",
    model: "ItemSlot",
    typeId: "helmet",
  },
  {
    _id: "60f188c8009f151f2379dc80",
    text: "Blackened with fire and ash.",
    model: "ItemSlot",
    typeId: "helmet",
  },
  {
    _id: "60f188f7009f151f2379dc81",
    text: "Lighter than you would expect but seems quite sturdy.",
    model: "ItemSlot",
    typeId: "helmet",
  },
  {
    _id: "60f1894e009f151f2379dc82",
    text: "Thin gold wire decorates the edges of the helmet.",
    model: "ItemSlot",
    typeId: "helmet",
  },
  {
    _id: "60f1899e009f151f2379dc83",
    text: "A small black feather decorates the helmet.",
    model: "ItemSlot",
    typeId: "helmet",
  },
  {
    _id: "60f189b4009f151f2379dc84",
    text: "A small plume of feathers stick out of the back of the helmet.",
    model: "ItemSlot",
    typeId: "helmet",
  },
  {
    _id: "60f189e4009f151f2379dc85",
    text: "The helmet has been embossed with the symbol of a mountain.",
    model: "ItemSlot",
    typeId: "helmet",
  },
  {
    _id: "60f18a00009f151f2379dc86",
    text: "The helmet has been embossed with the symbol of a bird.",
    model: "ItemSlot",
    typeId: "helmet",
  },
  {
    _id: "60f18a1f009f151f2379dc87",
    text: "The symbol of a tree has been painted onto the helmet.",
    model: "ItemSlot",
    typeId: "helmet",
  },
  {
    _id: "60f18a7f009f151f2379dc88",
    text: 'The words "Beasts Feasts" is engraved into the inside of the helmet.',
    model: "ItemSlot",
    typeId: "helmet",
  },
  {
    _id: "60f41dbb009f151f2379dc91",
    text: "This armour has impossible angles, it must have been created by some foul sorcery.",
    model: "ItemSlot",
    typeId: "body",
  },
  {
    text: "The cold steel helm feels reassuring, its interior lined with soft leather for comfort.",
    model: "ItemSlot",
    typeId: "helmet",
  },
  {
    text: "Inscribed with strange runes, this plate helmet emanates an otherworldly aura.",
    model: "ItemBase",
    typeId: "Plate Helmet",
  },
  {
    text: "Lightweight and unrestrictive, the leather armor molds to your body.",
    model: "ItemSlot",
    typeId: "body",
  },
  {
    text: "Crafted with intricate detail, the mail armor is a testament to the skills of the blacksmith.",
    model: "ItemBase",
    typeId: "Mail Armour",
  },
  {
    text: "The gloves are made of supple leather, offering both protection and dexterity.",
    model: "ItemSlot",
    typeId: "gloves",
  },
  {
    text: "Laced with golden threads, these silk gloves are both luxurious and charming.",
    model: "ItemBase",
    typeId: "Silk Gloves",
  },
  {
    text: "The boots are sturdy, constructed to withstand any terrain.",
    model: "ItemSlot",
    typeId: "boots",
  },
  {
    text: "Cobbled from fine leather, the boots are as stylish as they are practical.",
    model: "ItemBase",
    typeId: "Leather Boots",
  },
  {
    text: "The weapon is well-balanced, fitting comfortably in your grip.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    text: "The greatsword is as intimidating as it is deadly, etched with tales of valor and conquest.",
    model: "ItemBase",
    typeId: "Greatsword",
  },
  {
    text: "The jewelry shimmers softly, capturing the ambient light.",
    model: "ItemSlot",
    typeId: "jewelry",
  },
  {
    text: "The ring is forged from pure silver, etched with delicate scrollwork around the band.",
    model: "ItemBase",
    typeId: "Ring",
  },
  {
    text: "Practical and versatile, these items are more than they seem.",
    model: "ItemSlot",
    typeId: "misc",
  },
  {
    text: "The flask is crafted from sturdy glass, its cork secured by a wax seal.",
    model: "ItemBase",
    typeId: "Flask",
  },
  {
    text: "Beneath the rough exterior, an inner strength resides...",
    model: "ItemSlot",
    typeId: "body",
  },
  {
    text: "The amulet feels oddly warm, and pulses gently with an unseen energy.",
    model: "ItemBase",
    typeId: "Amulet",
  },
  {
    text: "A melody seems to hum softly from the weapon, a rhythm of battle long past...",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    text: "Made from dense wood and reinforced with iron, the club is a formidable tool in the right hands.",
    model: "ItemBase",
    typeId: "Club",
  },
  {
    text: "The soft glow of the helmet seems to bolster your courage...",
    model: "ItemSlot",
    typeId: "helmet",
  },
  {
    text: "Silk Robes, shimmering with ethereal colors under the light.",
    model: "ItemBase",
    typeId: "Silk Robes",
  },
  {
    text: "Despite their worn appearance, these leather boots seem capable of taking you anywhere.",
    model: "ItemSlot",
    typeId: "boots",
  },
  {
    text: "This greatclub is not just a weapon; it’s a statement...",
    model: "ItemBase",
    typeId: "Greatclub",
  },
  {
    text: "Subtle, yet powerful, the amulet beckons to the unseen...",
    model: "ItemSlot",
    typeId: "jewelry",
  },
  {
    text: "Gleaming under the sun, the warhammer is as sturdy as it looks.",
    model: "ItemBase",
    typeId: "Warhammer",
  },
  {
    text: "In battle, every ring may be a circle of protection...",
    model: "ItemSlot",
    typeId: "Ring",
  },
  {
    text: "The helmet, heavier than it seems, engulfs you in reassuring solitude. Its inner layer of cushioning softens the weight, adding comfort to security.",
    model: "ItemSlot",
    typeId: "helmet",
  },
  {
    text: "Imposing and magnificent, the Plate Helmet is covered in enigmatic symbols. A faint aura of power surrounds it, like an echo of battles fought and won.",
    model: "ItemBase",
    typeId: "Plate Helmet",
  },
  {
    text: "Like a second skin, the leather armor fits perfectly, following every curve of your body. Its reassuring solidity without constriction enables swift and deadly movements.",
    model: "ItemSlot",
    typeId: "body",
  },
  {
    text: "The Mail Armor is an exquisite testament to the blacksmith's prowess. Each link is meticulously crafted and intertwined, creating a flexible and reliable shield against harm.",
    model: "ItemBase",
    typeId: "Mail Armour",
  },
  {
    text: "Crafted with the agility of the archer in mind, these gloves ensure a firm grip on your weapon. The supple leather enhances your dexterity, allowing precision with each shot.",
    model: "ItemSlot",
    typeId: "gloves",
  },
  {
    text: "Woven with strands of gold, these silk gloves display elegance and charm. Their allure is not just in their appearance, but also in the subtle magic they hold within.",
    model: "ItemBase",
    typeId: "Silk Gloves",
  },
  {
    text: "As solid as the earth, these boots are made to endure. They fit firmly around your feet, ready to carry you across fields, through forests, or into the heart of battle.",
    model: "ItemSlot",
    typeId: "boots",
  },
  {
    text: "This pair of Leather Boots combine functionality and fashion. The supple leather is neatly stitched, forming a sturdy yet comfortable footwear fit for any adventure.",
    model: "ItemBase",
    typeId: "Leather Boots",
  },
  {
    text: "Your hand wraps comfortably around the hilt of the weapon. Its balance is perfect, attuned to your movements, promising swift victory to its master.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    text: "The Greatsword, engraved with stories of heroic deeds and epic battles, is a sight to behold. The blade gleams dangerously, a silent testament to the strength of its wielder.",
    model: "ItemBase",
    typeId: "Greatsword",
  },
  {
    text: "The jewelry catches the eye with its soft shimmer. Whether nestled in velvet or adorning a noble, the piece is a radiant beacon of wealth and status.",
    model: "ItemSlot",
    typeId: "jewelry",
  },
  {
    text: "Carved from lustrous gold, this ring is adorned with intricate engravings. The band feels cool against your skin, promising power to those who respect its value.",
    model: "ItemBase",
    typeId: "Ring",
  },
  {
    text: "Beyond their mundane exterior, these objects hold extraordinary potential. Each item holds its own secret, waiting to be unlocked by the right person.",
    model: "ItemSlot",
    typeId: "misc",
  },
  {
    text: "This Flask, forged from sturdy glass, is sealed with a wax emblem. The liquid within gleams enticingly, holding the promise of unknown effects.",
    model: "ItemBase",
    typeId: "Flask",
  },
  {
    text: "A Cloak of Shadow swirls around you, blending you into the night. Its secret lies not just in its material, but in the magic that imbues every thread.",
    model: "ItemSlot",
    typeId: "body",
  },
  {
    text: "The Quarterstaff is simple and unadorned, a reminder of the virtue in humility. Its true power lies not in appearance, but in the skill and grace of its user.",
    model: "ItemBase",
    typeId: "Quarterstaff",
  },
  {
    text: "This Longsword's blade shines like a beacon in the dark. Its edge, though sharp enough to cut through the air, whispers a song of power that only its true master can hear.",
    model: "ItemBase",
    typeId: "Longsword",
  },
  {
    text: "The Plate Boots, heavy and imposing, are engraved with symbols of protection. Each step in these boots is a testament to your unyielding determination.",
    model: "ItemBase",
    typeId: "Plate Boots",
  },
  {
    text: "This Plate Armour is a fortress that you wear. Its heavy plating is made to withstand the hardest blows, while the intricate design declares the status of the wearer.",
    model: "ItemBase",
    typeId: "Plate Armour",
  },
  {
    text: "An elegant Silk Robe, light and comfortable. The fabric is adorned with symbols and sigils, each meticulously embroidered, telling a story only the enlightened can understand.",
    model: "ItemBase",
    typeId: "Silk Robes",
  },
  {
    text: "With a grip that feels like an extension of your hand, the Dagger is as deadly as it is graceful. The blade catches the light, hinting at its sharpness and lethal potential.",
    model: "ItemBase",
    typeId: "Dagger",
  },
  {
    text: "This Crossbow, designed for precision, feels balanced and deadly in your hands. The intricately carved wood and masterfully forged iron are a testament to its maker.",
    model: "ItemBase",
    typeId: "Crossbow",
  },
  {
    text: "The Spear, noble and true, carries with it the spirit of the warrior. The balanced weight of the shaft and the sharpness of the point promise swift justice to any enemy.",
    model: "ItemBase",
    typeId: "Spear",
  },
  {
    text: "This Amulet carries an ethereal glow. The stone at its center pulses with an enchanting light, suggesting magic older than the land itself, waiting for its chosen to call.",
    model: "ItemBase",
    typeId: "Amulet",
  },
  {
    text: "The Belt, though plain in its appearance, serves an essential function. Its sturdiness and comfort remind you of the foundational things in life that often go unnoticed.",
    model: "ItemBase",
    typeId: "Belt",
  },
  {
    text: "This weapon, regardless of form, carries a weight that goes beyond its physical measure. It is a balance of power and finesse, a dance of life and death in your hands.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    text: "The weapon's structure embodies the very essence of conflict. Its form speaks of numerous encounters, each notch and wear a testament to battles won and lessons learned.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    text: "As your fingers wrap around the weapon's hilt, a surge of readiness courses through your veins. Regardless of shape or form, its potential for destruction - or salvation - is palpable.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    text: "The weapon's design is an eloquent poetry of functionality. Its purpose clear: to protect, to conquer, to prevail. Its nature transcends the boundary between range and melee.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    text: "In the hands of a master, this weapon could dictate the fate of kingdoms. Its silent promise of power and justice resonates with your warrior spirit.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    text: "This weapon, irrespective of its design, stands as a testament to the art of warfare. It is a silent companion that whispers tales of courage and valor to its wielder.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    text: "The gleam of the weapon holds a silent menace, a promise of the storm to come. It feels like an extension of your will, ready to unleash havoc at your command.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    text: "Holding the weapon, you feel a resonance, a hunger for battle. Its form, be it blade or bow, echoes the rhythm of combat, ready to dance to the music of warfare.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    text: "The weapon, a tangible manifestation of conflict and resolution, rests securely in your grasp. It is ready to serve, ready to defend, ready to conquer.",
    model: "ItemSlot",
    typeId: "weapon",
  },
  {
    text: "Embodying both grace and power, this weapon serves as a faithful companion. Its form, honed for battle, tells a tale of anticipation, ready to fulfill its purpose at your behest.",
    model: "ItemSlot",
    typeId: "weapon",
  },
];

export const findFlavorById = (_id) => {
  return ITEM_FLAVOR.find((flavor) => flavor?._id === _id);
};

export const getRandomFlavor = (slot, base) => {
  slot = slot.toLowerCase();
  base = base.toLowerCase();

  const availableFlavors = ITEM_FLAVOR.filter(
    (flavor) => flavor.typeId === slot || flavor.typeId === base
  );

  if (availableFlavors.length === 0) {
    return null; // Return null if there are no available flavors for the given slot or base.
  }

  const randomIndex = Math.floor(Math.random() * availableFlavors.length);
  return availableFlavors[randomIndex];
};
