export const ITEM_MODS = [
  {
    mod: "{+1} to AC",
    typeId: "helmet",
    model: "ItemSlot",
    flavor: null,
    prefix: "Hearty",
    suffix: "",
  },
  {
    mod: "{+1} to CON",
    typeId: "helmet",
    model: "ItemSlot",
    flavor: null,
    prefix: "Large",
    suffix: "",
  },
  {
    mod: "You have {+2} to stealth rolls with this helmet equipped",
    typeId: "helmet",
    model: "ItemSlot",
    flavor: null,
    prefix: "",
    suffix: "of Silence",
  },
  {
    mod: "You take {-2} fire damage",
    typeId: "helmet",
    model: "ItemSlot",
    flavor: null,
    prefix: "",
    suffix: "of Dousing",
  },
  {
    mod: "You take {-2} fire damage",
    typeId: "body",
    model: "ItemSlot",
    flavor: null,
    prefix: "",
    suffix: "of Dousing",
  },
  {
    mod: "Once per day you may change the appearance of this armour as a minor action",
    typeId: "body",
    model: "ItemSlot",
    flavor: null,
    prefix: "Shapshifting",
    suffix: "",
  },
  {
    mod: "{+1} to AC",
    typeId: "body",
    model: "ItemSlot",
    flavor: null,
    prefix: "Quality",
    suffix: "",
  },
  {
    mod: "Once per day you may re-roll a single dice as a free action",
    typeId: "gloves",
    model: "ItemSlot",
    flavor: null,
    prefix: "Lucky",
    suffix: "",
  },
  {
    mod: "When equipped, take 50% reduced damage from falling",
    typeId: "boots",
    model: "ItemSlot",
    flavor: null,
    prefix: "",
    suffix: "of Feather Fall",
  },
  {
    mod: "{+2} to Acrobatics",
    typeId: "boots",
    model: "ItemSlot",
    flavor: null,
    prefix: "",
    suffix: "of Acrobatics",
  },
  {
    mod: "{+1} to attack rolls",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: null,
    prefix: "Quality",
    suffix: "",
  },
  {
    mod: "You can choose to have this weapon deal fire damage",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: null,
    prefix: "",
    suffix: "of Flames",
  },
  {
    mod: "You can choose to have this weapon deal cold damage",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: null,
    prefix: "",
    suffix: "of Ice",
  },
  {
    mod: "Once per day, as an action, you may 'prime' this weapon. When primed, you have advantage on your next attack roll",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: null,
    prefix: "",
    suffix: "of Patience",
  },
  {
    mod: "Whenever you score a critical hit, you recover health equal to {+20}% of the damage dealt",
    typeId: "jewelry",
    model: "ItemSlot",
    flavor: null,
    prefix: "Vamping",
    suffix: "of Leeching",
  },
  {
    mod: "{+2} to Religion",
    typeId: "jewelry",
    model: "ItemSlot",
    flavor: null,
    prefix: "Holy",
    suffix: "",
  },
  {
    mod: "{+3} to Nature when you are outside",
    typeId: "jewelry",
    model: "ItemSlot",
    flavor: null,
    prefix: "",
    suffix: "of the Earth",
  },
  {
    mod: "Arrows have a 50% chance to pierce their target and deal an additional 1d4 of damage",
    typeId: "Shortbow",
    model: "ItemBase",
    flavor: null,
    prefix: "Piercing",
    suffix: "",
  },
  {
    mod: "Bolts have a 50% chance to pierce their target and deal an additional 1d4 of damage",
    typeId: "Crossbow",
    model: "ItemBase",
    flavor: null,
    prefix: "Piercing",
    suffix: "",
  },
  {
    mod: "This belt has a hidden compartment that small items can be stored in. This compartment cannot be discovered by enemy checks",
    typeId: "Belt",
    model: "ItemBase",
    flavor: null,
    prefix: "",
    suffix: "of Security",
  },
  {
    mod: "{+2} to unarmed damage",
    typeId: "Ring",
    model: "ItemBase",
    flavor: null,
    prefix: "Chunky",
    suffix: "",
  },
  {
    mod: "{+2} to Intelligence",
    typeId: "Silk Hood",
    model: "ItemBase",
    flavor: null,
    prefix: "Wizard",
    suffix: "",
  },
  {
    mod: "{+2} to Dexterity",
    typeId: "Leather Helmet",
    model: "ItemBase",
    flavor: null,
    prefix: "Hunter",
    suffix: "",
  },
  {
    mod: "{+2} to Medicine rolls",
    typeId: "Silk Robes",
    model: "ItemBase",
    flavor: null,
    prefix: "Healing",
    suffix: "",
  },
  {
    mod: "{+2} to History rolls",
    typeId: "Silk Robes",
    model: "ItemBase",
    flavor: null,
    prefix: "",
    suffix: "of Knowledge",
  },
  {
    mod: "{+1} to attack rolls made with a ranged weapon",
    typeId: "Leather Armour",
    model: "ItemBase",
    flavor: null,
    prefix: "",
    suffix: "of Accuracy",
  },
  {
    mod: "Enemies cannot knock you down. {-1} to Stealth rolls",
    typeId: "Plate Boots",
    model: "ItemBase",
    flavor: null,
    prefix: "Holdfast",
    suffix: "",
  },
  {
    mod: "Once this ring is donned, it cannot be removed",
    typeId: "Ring",
    model: "ItemBase",
    flavor: null,
    prefix: "Sticky",
    suffix: "",
  },
  {
    mod: "{+2} to AC",
    typeId: "body",
    model: "ItemSlot",
    flavor: null,
    prefix: "Resilient",
    suffix: "",
  },
  {
    mod: "You can jump {+3} times the normal distance",
    typeId: "boots",
    model: "ItemSlot",
    flavor: null,
    prefix: "",
    suffix: "of Leeping",
  },
  {
    mod: "While wearing these gloves, climbing doesn't cost you extra movement and you gain {+5} to Athletics checks made to climb",
    typeId: "gloves",
    model: "ItemSlot",
    flavor: null,
    prefix: "Climbing",
    suffix: "",
  },
  {
    mod: "While wearing these gloves, swimming doesn't cost you extra movement and you gain {+5} to Athletics checks made to swim",
    typeId: "gloves",
    model: "ItemSlot",
    flavor: null,
    prefix: "Merwood",
    suffix: "",
  },
  {
    mod: "While wearing these dark lenses, you have darkvision out to a range of {60} feet. If you already have darkvision, wearing the goggles increases its range by {60} feet",
    typeId: "Goggles",
    model: "ItemBase",
    flavor: null,
    prefix: "Nighvision",
    suffix: "",
  },
  {
    mod: "{+2} to attack rolls",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: null,
    prefix: "",
    suffix: "",
  },
  {
    mod: "This potion’s container looks empty but feels as though it holds liquid. When you drink it, you become invisible for 1 hour. Anything you wear or carry is invisible with you. The effect ends early if you attack or cast a spell",
    typeId: "Flask",
    model: "ItemBase",
    flavor: null,
    prefix: "",
    suffix: "of Invisibility",
  },
  {
    mod: "When you drink this potion, you gain a flying speed equal to your walking speed for 1 hour and can hover. If you’re in the air when the potion wears off, you fall unless you have some other means of staying aloft",
    typeId: "Flask",
    model: "ItemBase",
    flavor: "5e21e448f72b50317c3ce1d3",
    prefix: "",
    suffix: "of Flying",
  },
  {
    mod: "When you hit a creature with this weapon, that creature must make a {DC 14 CON} saving throw or be poisoned until the start of your next turn",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: "5e21e5a0f72b50317c3ce1d8",
    prefix: "Sickly",
    suffix: "",
  },
  {
    mod: "If a creature takes lethal damage from this weapon it immediately explodes apart in a burst of pale-blue light, dealing this weapons damage to everything within {5ft}",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: null,
    prefix: "Detonate",
    suffix: "",
  },
  {
    mod: "This weapon gains the thrown (range 30/90) property, and will always return to you after you make a ranged attack with it, even if you hit",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: null,
    prefix: "",
    suffix: "of Valhalla",
  },
  {
    mod: "This weapon deals an additional {1d4} lightning damage, double the damage if the target is wearing metal armour.",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: null,
    prefix: "Shocking",
    suffix: "",
  },
  {
    mod: "You have {+2} to attack and damage rolls against undead with this weapon",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: null,
    prefix: "Holy",
    suffix: "Bane of the Dead",
  },
  {
    mod: "You can make attacks with these gloves for {1d8} damage",
    typeId: "gloves",
    model: "ItemSlot",
    flavor: "5e21ea87f72b50317c3ce1e4",
    prefix: "Bear",
    suffix: "of the Bear",
  },
  {
    mod: "Critical hits with this weapon deal an additional {2d6} damage of this weapons damage type",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: null,
    prefix: "Vicious",
    suffix: "",
  },
  {
    mod: "You gain a {+2} bonus to AC against ranged attacks while you wield this shield. This bonus is in addition to the shield’s normal bonus to AC. In addition, whenever an attacker makes a ranged attack against a target within {5} feet of you, you can use your reaction to become the target of the attack instead.",
    typeId: "Shield",
    model: "ItemBase",
    flavor: null,
    prefix: "Arrow-Catching",
    suffix: "",
  },
  {
    mod: "Each successful hit with this weapon provides the wielder with {+2} temporary HP.",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: null,
    prefix: "",
    suffix: "",
  },
  {
    mod: "While wearing these bracers, you have proficiency with the longbow and shortbow, and you gain a {+2} bonus to damage rolls on ranged attacks made with such weapons.",
    typeId: "gloves",
    model: "ItemSlot",
    flavor: null,
    prefix: "",
    suffix: "of Archery",
  },
  {
    mod: "While wearing these bracers, you gain a {+2} bonus to AC if you are wearing no armor and using no shield.",
    typeId: "gloves",
    model: "ItemSlot",
    flavor: null,
    prefix: "",
    suffix: "of Defense",
  },
  {
    mod: "While wearing this amulet, you can use an action to cast the {scorching ray} spell with it. When you make the spell’s attacks, you do so with an attack bonus of {+5}. The amulet can’t be used this way again until the next dawn.",
    typeId: "Amulet",
    model: "ItemBase",
    flavor: null,
    prefix: "Scorching",
    suffix: "of Blasting",
  },
  {
    mod: "These arrows immolate on impact, dealing an extra {1d8} fire damage. The immolation destroys the arrow and it cannot be recovered.",
    typeId: "Arrows (20)",
    model: "ItemBase",
    flavor: null,
    prefix: "Firedart",
    suffix: "",
  },
  {
    mod: "The arrows cause a shockwave on impact and knock the target backwards {5ft}, they also cause an additional {1d4} force damage. The shockwave destroys the arrow and it cannot be recovered.",
    typeId: "Arrows (20)",
    model: "ItemBase",
    flavor: null,
    prefix: "Force",
    suffix: "",
  },
  {
    mod: "The belt creates and holds up to 6 thunderbolt-shaped magic darts. A hit with one of these magic darts deals an extra {1d6} lightning damage. After a successful hit, the dart disappears. Each day at dawn, {1d6 + 1} new darts are created by the belt, replacing any that have disappeared.",
    typeId: "Belt",
    model: "ItemBase",
    flavor: "5e2642b94f6bdd7ef1745260",
    prefix: "Zeus's",
    suffix: "",
  },
  {
    mod: "You gain a {+1} bonus to your AC and a {+5} bonus to your base movement speed if wearing light or no armor while wearing this belt. Additionally, your damage die for your unarmed strikes goes up by 1 die increment to a max of {1d12}.",
    typeId: "Belt",
    model: "ItemBase",
    flavor: "5e2643ab4f6bdd7ef1745262",
    prefix: "Monk's",
    suffix: "",
  },
  {
    mod: "Natural rolls of 19 or 20 when attacking are considered critical hits when using this weapon.",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: null,
    prefix: "Lucky",
    suffix: "",
  },
  {
    mod: "Upon killing an enemy with an unarmed strike you regenerate health equal to your constitution modifier.",
    typeId: "gloves",
    model: "ItemSlot",
    flavor: null,
    prefix: "Crushing",
    suffix: "",
  },
  {
    mod: "While wearing this armor, you have {+2} bonus to Strength-based weapon damage rolls.",
    typeId: "body",
    model: "ItemSlot",
    flavor: null,
    prefix: "Barbarian",
    suffix: "",
  },
  {
    mod: "You can use your action to smash your hammer into the ground. All creatures within a {10ft} radius of you must succeed on a Strength saving throw or fall prone. The DC is 8 + your Strength modifier + your proficiency bonus.",
    typeId: "Warhammer",
    model: "ItemBase",
    flavor: null,
    prefix: "",
    suffix: "of Vibrations",
  },
  {
    mod: "If you uncork the flask gently, it will pour out a stream of honey (about a pint) as an action. If shaken before opening, the flask produces an angry swarm of bees.",
    typeId: "Flask",
    model: "ItemBase",
    flavor: null,
    prefix: "",
    suffix: "of Bees",
  },
  {
    mod: "The staff has {3} charges. You can expend a charge and use your action to make a melee attack and deal {1d4} bludgeoning damage to a willing creature within reach. After the damage is dealt, the target regains {1d4} hit points per point of damage dealt. The staff regains {1} charge daily at dawn.",
    typeId: "Quarterstaff",
    model: "ItemBase",
    flavor: null,
    prefix: "Healing",
    suffix: "",
  },
  {
    mod: "When attacked with a melee weapon, the attacker has a {20%} chance to bleed for {1d4} damage at the start of its next turn",
    typeId: "Studded Leather Armour",
    model: "ItemBase",
    flavor: null,
    prefix: "Sharp",
    suffix: "of Spikes",
  },
  {
    mod: "You have resistance to {cold} type damage",
    typeId: "gloves",
    model: "ItemSlot",
    flavor: null,
    prefix: "Mollifying",
    suffix: "of the Thaw",
  },
  {
    mod: "Crackling with the sharp snap of electricity, this weapon deals {lightning} damage and has {20%} increased damage against targets wearing metal.",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: null,
    prefix: "Crackling",
    suffix: "of Lightning",
  },
  {
    mod: "Covered in filth and mold, this weapon deals {+1d4} {poison} damage on hit.",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: "5e21e5a0f72b50317c3ce1d8",
    prefix: "Vile",
    suffix: "of Filth",
  },
  {
    mod: "Light emanates from a single crack in this weapon. You may deal {+1d4} {radiant} damage on hit.",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: null,
    prefix: "Hallowed",
    suffix: "of the Faithful",
  },
  {
    mod: "There is a mystical eye carved into this weapon. If someone looks directly into the eye they must make a {DC 15 CON} save or suffer {1d12} {psychic} damage.",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: "5f1ef961493c895c310de6b8",
    prefix: "Fear",
    suffix: "of Seeking",
  },
  {
    mod: "Wind seems to surround this weapon. You may deal {+1d4} {force} damage on hit.",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: null,
    prefix: "Gale",
    suffix: "",
  },
  {
    mod: "The weapon drips with acid that burns the skin. You may deal {+1d4} {acid} damage on hit.",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: null,
    prefix: "Corrosive",
    suffix: "",
  },
  {
    mod: "When this weapon makes contact a thunderclap echoes around it dealing {1d4} {thunder} damage to everyone except the wielder in a {5ft} radius.",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: null,
    prefix: "Booming",
    suffix: "of Thunder",
  },
  {
    mod: "You have {+2} to attack and damage rolls with this weapon.",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: null,
    prefix: "Cruel",
    suffix: "",
  },
  {
    mod: "You have {+3} to attack and damage rolls with this weapon.",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: null,
    prefix: "Merciless",
    suffix: "",
  },
  {
    mod: "You have {+1} to attack and damage rolls with this weapon.",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: null,
    prefix: "Serrated",
    suffix: "",
  },
  {
    mod: "When you roll a {20} on an attack roll with this weapon you deal an additional {1d8} damage. ",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: null,
    prefix: "Bloodthirsty",
    suffix: "of Incision",
  },
  {
    mod: "When you roll a {20} on an attack roll with this weapon you gain the damage dealt as temporary hit points.",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: null,
    prefix: "",
    suffix: "of Nourishment",
  },
  {
    mod: "You may use an action to cause oily, red pus to coat the blade. The pus remains for 1 minute or until an attack with this weapon hits. The hit creature must make a {DC 15 CON} save or take {2d6} {necrotic} damage and become poisoned for 1 minute.",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: null,
    prefix: "Eldrich",
    suffix: "",
  },
  {
    mod: "You may use an action to cause thick, black poison to coat the blade. The poison remains for 1 minute or until an attack with this weapon hits. The hit creature must make a {DC 15 CON} save or take {1d10} {poison} damage and become poisoned for 1 minute.",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: null,
    prefix: "Venomous",
    suffix: "",
  },
  {
    mod: "As an action you may freeze all liquids within {40ft} for 1 minute.",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: "5f1ef800493c895c310de6b3",
    prefix: "Whiteout",
    suffix: "of the Squall",
  },
  {
    mod: "When you hit a creature with this weapon they must make a {DC 15 DEX} save or be immobilized during their next turn.",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: null,
    prefix: "Achilles",
    suffix: "of Crippling",
  },
  {
    mod: "You may make one attack with this weapon as a {bonus action} on each of your turns.",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: null,
    prefix: "Quick",
    suffix: "of Speed",
  },
  {
    mod: "This weapon has {3} charges. If the target is standing on soil you may expend a charge as an action to have vines grow from the soil and entangle the target. They are paralyzed until they make a {DC 15 STR} save to escape. The charges replenish with a long rest.",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: "5f1ef7ec493c895c310de6b2",
    prefix: "Entangling",
    suffix: "of the Dryads",
  },
  {
    mod: "Once per day as a free action you may name a creature as your {sworn enemy}. You may only have {1} sworn enemy at a given time. You have advantage on attack rolls against your sworn enemies. When you kill a sworn enemy gain {1d4} temporary hit points.",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: null,
    prefix: "Oathkeeping",
    suffix: "of Vengeance",
  },
  {
    mod: "You may cast a spell without expending a {spell slot}. Recharges on a long rest.",
    typeId: "jewelry",
    model: "ItemSlot",
    flavor: null,
    prefix: "Glyphic",
    suffix: "of Improvment",
  },
  {
    mod: "{+1} to saving throws",
    typeId: "body",
    model: "ItemSlot",
    flavor: null,
    prefix: "Resilient",
    suffix: "of  Sturdiness",
  },
  {
    mod: "Arrows have a {50%} chance to pierce their target and deal an additional {1d4} damage",
    typeId: "Longbow",
    model: "ItemBase",
    flavor: null,
    prefix: "Piercing",
    suffix: "",
  },
  {
    mod: "This weapon has {1d8} charges. If you score a critical hit with this weapon on a creature with less then {100 hp} it must make a {DC 15 CON} save or this weapon tears the {soul} from its body, immediately killing it and consuming a charge. When all the charges are consumed this weapon is immediately destroyed and the souls it has consumed are summoned as {undead} enemies with the same stats as when they were slain.",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: "5f1ed1ab493c895c310de665",
    prefix: "Hungering",
    suffix: "of Souls",
  },
  {
    mod: "You may speak the command word to have this weapon shed bright light for {10ft} and dim light for an additional {10ft}. Speaking the command word end this effect.",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: null,
    prefix: "Bright",
    suffix: "of Guiding",
  },
  {
    mod: "You may speak the true name of a creature in the mortal plane and the amulet will gently pull in the direction of that creature. ",
    typeId: "Amulet",
    model: "ItemBase",
    flavor: null,
    prefix: "Guiding",
    suffix: "of Tracking",
  },
  {
    mod: "As an action you may have this weapon emit a piercingly loud shriek. Targets you choose within {20ft} must make a {DC 15 CON} save or loose all hearing for {1d8 hours}. The shriek can be heard within {1 mile}",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: null,
    prefix: "Earshock",
    suffix: "of Shrieking",
  },
  {
    mod: "You may {plant} and {un-plant} yourself as an action, while planted you may not move. Enemies have {disadvantage} on attacks against you while you are planted",
    typeId: "Shield",
    model: "ItemBase",
    flavor: "5f2096f069172e05524a5b6d",
    prefix: "Barrier",
    suffix: "of the Hammer",
  },
  {
    mod: "when you are the target of a spell you may attempt to make a {DC 15 STR} check. If you {succeed} you may reflect the spell back at the caster dealing half damage. If you {fail} you take double damage from the spell.",
    typeId: "Shield",
    model: "ItemBase",
    flavor: "5f20994569172e05524a5b6f",
    prefix: "Mirror",
    suffix: "",
  },
  {
    mod: "Once per day when you are the target of a spell you may challenge the caster to a skill contest. If you win the spell has no effect, otherwise the spell acts as normal.",
    typeId: "Silk Hood",
    model: "ItemBase",
    flavor: null,
    prefix: "Negating",
    suffix: "of the Mind",
  },
  {
    mod: "Once per day when you are the target of a spell you may challenge the caster to a skill contest. If you win the spell has no effect, otherwise the spell acts as normal.",
    typeId: "Silk Robes",
    model: "ItemBase",
    flavor: null,
    prefix: "Negating",
    suffix: "of the Mind",
  },
  {
    mod: "{+2} to Sleight of Hand",
    typeId: "gloves",
    model: "ItemSlot",
    flavor: null,
    prefix: "Nimble",
    suffix: "of Infamy",
  },
  {
    mod: "{+2} to Acrobatics",
    typeId: "gloves",
    model: "ItemSlot",
    flavor: null,
    prefix: "Skill",
    suffix: "of Acrobatics",
  },
  {
    mod: "{+1} to Dexterity",
    typeId: "gloves",
    model: "ItemSlot",
    flavor: null,
    prefix: "Hollow",
    suffix: "of the Palm",
  },
  {
    mod: "{+2} to Stealth",
    typeId: "gloves",
    model: "ItemSlot",
    flavor: null,
    prefix: "Acclaimed",
    suffix: "of the Night",
  },
  {
    mod: "Knots tied with these gloves can only be undone with these same gloves or otherwise cutting the rope",
    typeId: "gloves",
    model: "ItemSlot",
    flavor: null,
    prefix: "Sailor's",
    suffix: "of Binding",
  },
  {
    mod: "While you wear these boots, your steps make no sound, regardless of the surface you are moving on. You also have advantage on {Stealth} checks that rely on moving silently.",
    typeId: "Cloth Boots",
    model: "ItemBase",
    flavor: null,
    prefix: "Silent",
    suffix: "of Elvenkind",
  },
  {
    mod: "While you wear these boots, your steps make no sound, regardless of the surface you are moving on. You also have advantage on {Stealth} checks that rely on moving silently.",
    typeId: "Leather Boots",
    model: "ItemBase",
    flavor: null,
    prefix: "Silent",
    suffix: "of Elvenkind",
  },
  {
    mod: "You can swim {twice} as fast as normal",
    typeId: "boots",
    model: "ItemSlot",
    flavor: null,
    prefix: "Webbed",
    suffix: "of the Toad",
  },
  {
    mod: "Once per day, if you succeed in a {DC 10 STR} check you may kick in an unlocked door, breaking it off its hinges an launching it into the room up to {15ft}. If the door collides with any creatures it deals {1d6} bludgeoning damage",
    typeId: "boots",
    model: "ItemSlot",
    flavor: null,
    prefix: "Doorman's",
    suffix: "of Busting",
  },
  {
    mod: "{+2} to Arcana",
    typeId: "Amulet",
    model: "ItemBase",
    flavor: null,
    prefix: "Wizard's",
    suffix: "of the Sage",
  },
  {
    mod: "{+2} to Medicine",
    typeId: "jewelry",
    model: "ItemSlot",
    flavor: null,
    prefix: "Stout",
    suffix: "of Nursing",
  },
  {
    mod: "This shield will glow when a creature aims a ranged weapon at you. The intensity of the glow indicated the distance of the creature",
    typeId: "Shield",
    model: "ItemBase",
    flavor: null,
    prefix: "",
    suffix: "of Warning",
  },
  {
    mod: "Drinking from this flask makes the consumer overcome with procrastinative thoughts. They will be unable to do or work on anything productive for the next {keyword_int} {hours}, no matter how hard they try.",
    typeId: "Flask",
    model: "ItemBase",
    flavor: null,
    prefix: "Lazy",
    suffix: "of the Inevitable",
  },
  {
    mod: "Unknowingly to the wearer, this item pressures the mind of its wearer to eliminate anyone with knowledge of this item. Over time this pressure is harder and harder to resist. What is secret must stay secret.",
    typeId: "jewelry",
    model: "ItemSlot",
    flavor: "5f26d4563d68df03ebb7fe5c",
    prefix: "Unseen",
    suffix: "of the Unknown",
  },
  {
    mod: "Once per day, you may choose a willing target and have the effect of gravity on it inverted for {keyword_int} {minutes} or until they choose to end it.",
    typeId: "jewelry",
    model: "ItemSlot",
    flavor: null,
    prefix: "Void",
    suffix: "of Inversion",
  },
  {
    mod: "Once per day you may choose any target and they must make a {keyword_attribute_short_check:10} or have the force of gravity on them inverted for {keyword_int} {seconds}.",
    typeId: "jewelry",
    model: "ItemSlot",
    flavor: null,
    prefix: "Reversal",
    suffix: "of the Up",
  },
  {
    mod: "{+}{keyword_int:3} to {Arcana}",
    typeId: "jewelry",
    model: "ItemSlot",
    flavor: null,
    prefix: "Magicians",
    suffix: "of the Spheres",
  },
  {
    mod: "{+}{keyword_int:3} to {Investigation}",
    typeId: "jewelry",
    model: "ItemSlot",
    flavor: null,
    prefix: "Searching",
    suffix: "of Investigation",
  },
  {
    mod: "{+}{keyword_int:3} to {Animal Handling}.",
    typeId: "jewelry",
    model: "ItemSlot",
    flavor: null,
    prefix: "Mild",
    suffix: "of the Disciplined",
  },
  {
    mod: "{+}{keyword_int:3} to {Perception}",
    typeId: "Goggles",
    model: "ItemBase",
    flavor: null,
    prefix: "Acute",
    suffix: "of Perception",
  },
  {
    mod: "{+}{keyword_int:3} to {Survival}",
    typeId: "jewelry",
    model: "ItemSlot",
    flavor: null,
    prefix: "Continuous",
    suffix: "of the Hermit",
  },
  {
    mod: "{+}{keyword_int:3} to {Deception}",
    typeId: "jewelry",
    model: "ItemSlot",
    flavor: null,
    prefix: "False",
    suffix: "of the Trickster",
  },
  {
    mod: "{+}{keyword_int:3} to {Intimidation}",
    typeId: "jewelry",
    model: "ItemSlot",
    flavor: null,
    prefix: "Gnashed",
    suffix: "of the Goliath",
  },
  {
    mod: "{+}{keyword_int:3} to {Performance}",
    typeId: "jewelry",
    model: "ItemSlot",
    flavor: null,
    prefix: "Wondrous",
    suffix: "of the Show",
  },
  {
    mod: "{+}{keyword_int:3} to {Persuasion}",
    typeId: "jewelry",
    model: "ItemSlot",
    flavor: null,
    prefix: "Convincing",
    suffix: "of the Debater",
  },
  {
    mod: "This flask can hold much more liquid then it first appears without becoming too heavy. ",
    typeId: "Flask",
    model: "ItemBase",
    flavor: null,
    prefix: "",
    suffix: "of Holding",
  },
  {
    mod: "Liquid stays hot in this flask eternally.",
    typeId: "Flask",
    model: "ItemBase",
    flavor: null,
    prefix: "Heated",
    suffix: "",
  },
  {
    mod: "Liquid stays {cold} in this flask eternally.",
    typeId: "Flask",
    model: "ItemBase",
    flavor: null,
    prefix: "Yeti",
    suffix: "",
  },
  {
    mod: "Drinking the entirety of this flask gives a temporary ({keyword_int:5} {min}) boost of {4} to {keyword_attribute}",
    typeId: "Flask",
    model: "ItemBase",
    flavor: null,
    prefix: "Gift",
    suffix: "of Perks",
  },
  {
    mod: "When you hit a creature they must make a {keyword_attribute_check} or have their movement speed halved until the end of their next turn.",
    typeId: "Arrows (20)",
    model: "ItemBase",
    flavor: null,
    prefix: "Crippling",
    suffix: "of Chains",
  },
  {
    mod: "When you hit a creature with these arrows from over {300ft} away, deal {double} damage",
    typeId: "Arrows (20)",
    model: "ItemBase",
    flavor: null,
    prefix: "Longshot",
    suffix: "of Assassination",
  },
  {
    mod: "When a creature is hit it must make a {keyword_attribute_check} or be unable to speak until the end of their next turn. Additionally, they must continue to make the save each turn unless they remove the arrow",
    typeId: "Arrows (20)",
    model: "ItemBase",
    flavor: null,
    prefix: "Silent",
    suffix: "of the Mute",
  },
  {
    mod: "You may have these arrows deal {keyword_damage_type} damage instead of their normal damage type",
    typeId: "Arrows (20)",
    model: "ItemBase",
    flavor: null,
    prefix: "Elemental",
    suffix: "",
  },
  {
    mod: "When a creature is hit it must make a {keyword_attribute_check} or be ignited. Ignited targets take {1d4 fire} damage at the start of their turn and must pass the ability check to end the effect",
    typeId: "Arrows (20)",
    model: "ItemBase",
    flavor: null,
    prefix: "Ignition",
    suffix: "of Flammability",
  },
  {
    mod: "Each arrow has a coil of strong wire contained in its shaft. If you use a bonus action to anchor the wire before shooting at a solid surface it will result in a cable stretched between the two objects, solid enough to walk across",
    typeId: "Arrows (20)",
    model: "ItemBase",
    flavor: null,
    prefix: "Tightrope",
    suffix: "of the Heist",
  },
  {
    mod: "When this arrow makes contact the head splits open and {acid} spills out. On top of the normal damage it also deals an additional {1d4 acid} damage.",
    typeId: "Arrows (20)",
    model: "ItemBase",
    flavor: null,
    prefix: "Acid",
    suffix: "",
  },
  {
    mod: "You have a {+}{keyword_int:5} bonus to attack rolls if the target creature is unaware of your presence",
    typeId: "Arrows (20)",
    model: "ItemBase",
    flavor: null,
    prefix: "Sneak",
    suffix: "of First Strike",
  },
  {
    mod: "When you hit a small creature with this net arrow it is knocked prone and restrained. Useful for catching small game",
    typeId: "Arrows (20)",
    model: "ItemBase",
    flavor: null,
    prefix: "Net",
    suffix: "of the Net",
  },
  {
    mod: "At the start of your next turn after firing one of these arrows, a lightning bolt will fall from the sky at the location of the arrow, dealing {2d4 lightning} damage to any creatures within {5ft}",
    typeId: "Arrows (20)",
    model: "ItemBase",
    flavor: null,
    prefix: "Lightning Strike",
    suffix: "of Clap",
  },
  {
    mod: "You have {+}{keyword_int:15:5}{ft} movement speed.",
    typeId: "helmet",
    model: "ItemSlot",
    flavor: "5f63abd879c7000d931539ef",
    prefix: "Mercury",
    suffix: "of the Messenger",
  },
  {
    mod: "When a creature hits you with a melee attack they must make a {keyword_attribute_short_check} check or take {1d3} damage per hit.",
    typeId: "body",
    model: "ItemSlot",
    flavor: null,
    prefix: "Spiked",
    suffix: "of Thorns",
  },
  {
    mod: "These boots do not leave behind any footprints. As a minor action you may have the boots instead leave behind footprints of any shape you desire.",
    typeId: "boots",
    model: "ItemSlot",
    flavor: null,
    prefix: "Fools",
    suffix: "of the Tracker",
  },
  {
    mod: "You take no extra critical hit damage from {keyword_enemy_type} type creatures.",
    typeId: "helmet",
    model: "ItemSlot",
    flavor: null,
    prefix: "Humbling",
    suffix: "of Oversight",
  },
  {
    mod: "Once per day you may {sidestep} a melee attack as a reaction. When you sidestep an attack in this way you may move up to {5ft} in any direction and it is as if the enemy missed you entirely.",
    typeId: "boots",
    model: "ItemSlot",
    flavor: null,
    prefix: "Juke",
    suffix: "of the Nimble",
  },
  {
    mod: "You have {+15ft} movement speed",
    typeId: "boots",
    model: "ItemSlot",
    flavor: null,
    prefix: "Seven-League",
    suffix: "of Speed",
  },
  {
    mod: "When stepping into water (or any liquid) you may choose instead to walk atop said liquid.",
    typeId: "boots",
    model: "ItemSlot",
    flavor: null,
    prefix: "Water Walking",
    suffix: "of Buoyancy",
  },
  {
    mod: "You ignore the movement penalties of {difficult terrain}.",
    typeId: "boots",
    model: "ItemSlot",
    flavor: null,
    prefix: "Steady",
    suffix: "of Stability",
  },
  {
    mod: "You have {+}{keyword_int:4} to {Initiative}.",
    typeId: "boots",
    model: "ItemSlot",
    flavor: "5f63b3d179c7000d931539f9",
    prefix: "Hasted",
    suffix: "of Action",
  },
  {
    mod: "When an attack is made against a friendly creature that's within {5ft}, you may consume a charge and give the friendly creature {+1AC} against that attack. A long rest restores this item to it's maximum of {keyword_range:2:5} charges.",
    typeId: "Shield",
    model: "ItemBase",
    flavor: "5f2096f069172e05524a5b6d",
    prefix: "Sentinel",
    suffix: "",
  },
  {
    mod: "You can activate the shield as a bonus action. Each creature you choose within {30ft} of you and that can see you must make a {DC 15 Wisdom} saving throw. On a failed saving throw, that creature is frightened for {1 minute}, and continues to make saving throws to stop the effect at the end of their turn.",
    typeId: "Shield",
    model: "ItemBase",
    flavor: null,
    prefix: "Terrifying",
    suffix: "of Suffering",
  },
  {
    mod: "When an enemy makes a melee attack against you and misses you may strike them with the corner of this shield as a reaction, dealing {1d4 bludgeoning} damage.",
    typeId: "Shield",
    model: "ItemBase",
    flavor: null,
    prefix: "Reflexive",
    suffix: "of Counterstrike",
  },
  {
    mod: "You can smell danger, you have {+4} on {Perception} checks to detect enemies.",
    typeId: "helmet",
    model: "ItemSlot",
    flavor: null,
    prefix: "Spidey",
    suffix: "of Sensing",
  },
  {
    mod: "Once per day you may use the {all or nothing} ability. Your next hit with this weapon is a critical failure on a {1-10} or a critical success on an {11-20}.",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: "5f73a22a79c7000d93153a28",
    prefix: "Gambler's",
    suffix: "of Nothing",
  },
  {
    mod: "This club cannot drop a creature below {1} health, if a hit with this weapon would bring a creature below {1} health it is instead knocked unconscious.",
    typeId: "Club",
    model: "ItemBase",
    flavor: null,
    prefix: "Merciful",
    suffix: "of Grounding",
  },
  {
    mod: "Once attuned, you will always know this rings location.",
    typeId: "Ring",
    model: "ItemBase",
    flavor: null,
    prefix: "Homing",
    suffix: "of Tracking",
  },
  {
    mod: "Wearing this ring will cause the user to appear invisible to nearby creatures.",
    typeId: "Ring",
    model: "ItemBase",
    flavor: null,
    prefix: "Silmarillion",
    suffix: "",
  },
  {
    mod: "When this arrow penetrates soil, at start of the next round, an undead skeleton claws out of the ground in that square. The skeleton acts on its own initiative, and attacks the nearest living creature until reduced to 0 hit points.",
    typeId: "Arrows (20)",
    model: "ItemBase",
    flavor: null,
    prefix: "",
    suffix: "of the Hydra",
  },
  {
    mod: "You have {+2} to {Charisma} checks for {30} minutes after drinking from this flask.",
    typeId: "Flask",
    model: "ItemBase",
    flavor: "5f73a64a79c7000d93153a34",
    prefix: "Pirate's",
    suffix: "of Charisma",
  },
  {
    mod: "You gain a {+2} bonus to maintain your concentration on a spell.",
    typeId: "Silk Robes",
    model: "ItemBase",
    flavor: null,
    prefix: "",
    suffix: "of Concentration",
  },
  {
    mod: "Your maximum hit points are increased by {keyword_range:3:7}.",
    typeId: "body",
    model: "ItemSlot",
    flavor: null,
    prefix: "Vigorous",
    suffix: "of the Troll",
  },
  {
    mod: "Once per day, you may grant yourself advantage on a {Constitution} saving throw.",
    typeId: "body",
    model: "ItemSlot",
    flavor: null,
    prefix: "Sturdy",
    suffix: "of the Elephant",
  },
  {
    mod: "When you are the target of an attack roll, roll a {d20}. On a result of a {20}, the attack misses.",
    typeId: "body",
    model: "ItemSlot",
    flavor: null,
    prefix: "Exposure",
    suffix: "of Squat",
  },
  {
    mod: "Your {Strength} score is {19} while wearing this armour. Your {Intelligence} is decreased by {4}.",
    typeId: "Plate Armour",
    model: "ItemBase",
    flavor: null,
    prefix: "Ogreking",
    suffix: "of the Bull",
  },
  {
    mod: "Your {Intelligence} is {19} while you wear this robe. Your {Strength} is decreased by {4}.",
    typeId: "Silk Robes",
    model: "ItemBase",
    flavor: null,
    prefix: "Occult",
    suffix: "of Surging",
  },
  {
    mod: "Your {Dexterity} is {19} while you wear this robe. Your {Constitution} is decreased by {4}.",
    typeId: "Leather Armour",
    model: "ItemBase",
    flavor: null,
    prefix: "Fortune",
    suffix: "of Feats",
  },
  {
    mod: "Projectile attacks that target you are made with disadvantage.",
    typeId: "body",
    model: "ItemSlot",
    flavor: null,
    prefix: "Galewall",
    suffix: "",
  },
  {
    mod: "You have resistance to {Acid} damage.",
    typeId: "jewelry",
    model: "ItemSlot",
    flavor: null,
    prefix: "Acrid",
    suffix: "of Dulling",
  },
  {
    mod: "You have resistance to {Cold} damage.",
    typeId: "jewelry",
    model: "ItemSlot",
    flavor: null,
    prefix: "Frigid",
    suffix: "of Frost",
  },
  {
    mod: "You have resistance to {Fire} damage.",
    typeId: "jewelry",
    model: "ItemSlot",
    flavor: null,
    prefix: "Inferno",
    suffix: "of the Blaze",
  },
  {
    mod: "You have resistance to {Force} damage.",
    typeId: "jewelry",
    model: "ItemSlot",
    flavor: null,
    prefix: "Impulse",
    suffix: "of Fury",
  },
  {
    mod: "You have resistance to {Necrotic} damage.",
    typeId: "jewelry",
    model: "ItemSlot",
    flavor: null,
    prefix: "Baleful",
    suffix: "of Pestilence",
  },
  {
    mod: "You have resistance to {Poison} damage.",
    typeId: "jewelry",
    model: "ItemSlot",
    flavor: null,
    prefix: "Blighted",
    suffix: "of Venom",
  },
  {
    mod: "You have resistance to {Psychic} damage.",
    typeId: "jewelry",
    model: "ItemSlot",
    flavor: null,
    prefix: "Mystic",
    suffix: "of Clairvoyance",
  },
  {
    mod: "You have resistance to {Radiant} damage.",
    typeId: "jewelry",
    model: "ItemSlot",
    flavor: null,
    prefix: "Brilliant",
    suffix: "of Lament",
  },
  {
    mod: "You have resistance to {Thunder} damage.",
    typeId: "jewelry",
    model: "ItemSlot",
    flavor: null,
    prefix: "Discharge",
    suffix: "of Rumble",
  },
  {
    mod: "You have resistance to {Lightning} damage.",
    typeId: "jewelry",
    model: "ItemSlot",
    flavor: null,
    prefix: "Galvanized",
    suffix: "of Grounding",
  },
  {
    mod: "You have resistance to {Lightning} damage.",
    typeId: "helmet",
    model: "ItemSlot",
    flavor: null,
    prefix: "Galvanized",
    suffix: "of Grounding",
  },
  {
    mod: "You have resistance to {Thunder} damage.",
    typeId: "helmet",
    model: "ItemSlot",
    flavor: null,
    prefix: "Discharge",
    suffix: "of Rumble",
  },
  {
    mod: "You have resistance to {Radiant} damage.",
    typeId: "helmet",
    model: "ItemSlot",
    flavor: null,
    prefix: "Brilliant",
    suffix: "of Lament",
  },
  {
    mod: "You have resistance to {Psychic} damage.",
    typeId: "helmet",
    model: "ItemSlot",
    flavor: null,
    prefix: "Mystic",
    suffix: "of Clairvoyance",
  },
  {
    mod: "You have resistance to {Poison} damage.",
    typeId: "helmet",
    model: "ItemSlot",
    flavor: null,
    prefix: "Blighted",
    suffix: "of Venom",
  },
  {
    mod: "You have resistance to {Necrotic} damage.",
    typeId: "helmet",
    model: "ItemSlot",
    flavor: null,
    prefix: "Baleful",
    suffix: "of Pestilence",
  },
  {
    mod: "You have resistance to {Force} damage.",
    typeId: "helmet",
    model: "ItemSlot",
    flavor: null,
    prefix: "Impulse",
    suffix: "of Fury",
  },
  {
    mod: "You have resistance to {Fire} damage.",
    typeId: "helmet",
    model: "ItemSlot",
    flavor: null,
    prefix: "Inferno",
    suffix: "of the Blaze",
  },
  {
    mod: "You have resistance to {Cold} damage.",
    typeId: "helmet",
    model: "ItemSlot",
    flavor: null,
    prefix: "Frigid",
    suffix: "of Frost",
  },
  {
    mod: "You have resistance to {Acid} damage.",
    typeId: "helmet",
    model: "ItemSlot",
    flavor: null,
    prefix: "Acrid",
    suffix: "of Dulling",
  },
  {
    mod: "You have resistance to {Acid} damage.",
    typeId: "body",
    model: "ItemSlot",
    flavor: null,
    prefix: "Acrid",
    suffix: "of Dulling",
  },
  {
    mod: "You have resistance to {Radiant} damage.",
    typeId: "body",
    model: "ItemSlot",
    flavor: null,
    prefix: "Holy",
    suffix: "of Lament",
  },
  {
    mod: "You have resistance to {Cold} damage.",
    typeId: "body",
    model: "ItemSlot",
    flavor: null,
    prefix: "Frigid",
    suffix: "of Frost",
  },
  {
    mod: "You have resistance to {Fire} damage.",
    typeId: "body",
    model: "ItemSlot",
    flavor: null,
    prefix: "Inferno",
    suffix: "of the Blaze",
  },
  {
    mod: "You have resistance to {Force} damage.",
    typeId: "body",
    model: "ItemSlot",
    flavor: null,
    prefix: "Impulse",
    suffix: "of Fury",
  },
  {
    mod: "You have resistance to {Necrotic} damage.",
    typeId: "body",
    model: "ItemSlot",
    flavor: null,
    prefix: "Baleful",
    suffix: "of Pestilence",
  },
  {
    mod: "You have resistance to {Poison} damage.",
    typeId: "body",
    model: "ItemSlot",
    flavor: null,
    prefix: "Blighted",
    suffix: "of Venom",
  },
  {
    mod: "You have resistance to {Psychic} damage.",
    typeId: "body",
    model: "ItemSlot",
    flavor: null,
    prefix: "Mystic",
    suffix: "of Clairvoyance",
  },
  {
    mod: "You have resistance to {Thunder} damage.",
    typeId: "body",
    model: "ItemSlot",
    flavor: null,
    prefix: "Discharge",
    suffix: "of Rumble",
  },
  {
    mod: "You have resistance to {Lightning} damage.",
    typeId: "body",
    model: "ItemSlot",
    flavor: null,
    prefix: "Galvanized",
    suffix: "of Grounding",
  },
  {
    mod: "{+2} to Animal Handling.",
    typeId: "gloves",
    model: "ItemSlot",
    flavor: null,
    prefix: "Beast",
    suffix: "of the Brute",
  },
  {
    mod: "{+2} to Medicine.",
    typeId: "gloves",
    model: "ItemSlot",
    flavor: null,
    prefix: "Doctor's",
    suffix: "of Mending",
  },
  {
    mod: "{+2} to Survival.",
    typeId: "gloves",
    model: "ItemSlot",
    flavor: null,
    prefix: "Lasting",
    suffix: "of the Remains",
  },
  {
    mod: "{+2} to Survival.",
    typeId: "boots",
    model: "ItemSlot",
    flavor: null,
    prefix: "Lasting",
    suffix: "of the Ramains",
  },
  {
    mod: "{+2} to Athletics.",
    typeId: "boots",
    model: "ItemSlot",
    flavor: null,
    prefix: "Robust",
    suffix: "of Brawn",
  },
  {
    mod: "{+2} to Intimidation.",
    typeId: "gloves",
    model: "ItemSlot",
    flavor: null,
    prefix: "Terror",
    suffix: "of Coercion",
  },
  {
    mod: "{+2} to Intimidation.",
    typeId: "boots",
    model: "ItemSlot",
    flavor: null,
    prefix: "Terror",
    suffix: "of Coercion",
  },
  {
    mod: "{+2} to Performance.",
    typeId: "gloves",
    model: "ItemSlot",
    flavor: null,
    prefix: "Perky",
    suffix: "of Entertainment",
  },
  {
    mod: "{+2} to Persuasion.",
    typeId: "gloves",
    model: "ItemSlot",
    flavor: null,
    prefix: "Enticing",
    suffix: "of Seduction",
  },
  {
    mod: "{+2} to Persuasion.",
    typeId: "boots",
    model: "ItemSlot",
    flavor: null,
    prefix: "Enticing",
    suffix: "of Seduction",
  },
  {
    mod: "{+2} to Stealth.",
    typeId: "Cloth Boots",
    model: "ItemBase",
    flavor: null,
    prefix: "Covert",
    suffix: "of the Mouse",
  },
  {
    mod: "Creatures are inclined to sell you items at a reduced price.",
    typeId: "jewelry",
    model: "ItemSlot",
    flavor: null,
    prefix: "Flea",
    suffix: "Of Bartering",
  },
  {
    mod: "This weapon is held together with strong magic, it cannot be broken.",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: null,
    prefix: "Unbreaking",
    suffix: "Of the Unbroken",
  },
  {
    mod: "When you are the target of a ranged projectile attack you may attempt a {DC 15 Athletics} check to deflect the projectile with this shield. If you succeed you may retarget the projectile into any creature within {10ft} of yourself.",
    typeId: "Shield",
    model: "ItemBase",
    flavor: null,
    prefix: "Reflexive",
    suffix: "Of Deflection",
  },
  {
    mod: "You may make improvised weapon attacks with this shield for {2d8} bludgeoning damage.",
    typeId: "Shield",
    model: "ItemBase",
    flavor: null,
    prefix: "Spiked",
    suffix: "Of Thrashing",
  },
  {
    mod: "When thrown as a ranged weapon, this dagger will magically return to the user's hand, ready to be thrown again immediately. ",
    typeId: "Dagger",
    model: "ItemBase",
    flavor: null,
    prefix: "Throwing",
    suffix: "Of the Sparrow",
  },
  {
    mod: "Regain {2d4 +2} HP when you drink this flask.",
    typeId: "Flask",
    model: "ItemBase",
    flavor: null,
    prefix: "Healing",
    suffix: "Of Medicine",
  },
  {
    mod: "The wearer of this amulet sees the faces of dead heroes in the walls. Sometimes the dead heroes warn the wearer of incoming danger. ",
    typeId: "Amulet",
    model: "ItemBase",
    flavor: null,
    prefix: "Eidolon",
    suffix: "of Faces",
  },
  {
    mod: "When you reduce a creature that has blood to 0 HP using this weapon, the creature sprays a fountain of blood in a {10ft} radius covering creatures in the area with blood. Creatures coated in blood this way take an additional {1d8 Psychic} damage when struck with this weapon.",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: null,
    prefix: "Sanguine",
    suffix: "of Bloodletting",
  },
  {
    mod: "Once per day, when you miss an attack or when you're hit by an attack, you may tip the balance in your favor. Roll a {d4} and add or subtract the number respectively. ",
    typeId: "gloves",
    model: "ItemSlot",
    flavor: null,
    prefix: "Introspective",
    suffix: "of Balance",
  },
  {
    mod: "When a friendly creature within {keyword_range:20:50:5}{ft} is dealt damage you may roll {1d4}, subtract your roll from the damage dealt. This ability has {keyword_range:3:7} maximum charges, regenerate {1d4} charges during a long rest.",
    typeId: "jewelry",
    model: "ItemSlot",
    flavor: null,
    prefix: "Divine",
    suffix: "of Protection",
  },
  {
    mod: "Once per day, as an action you may activate an {aura of balance} that lasts for {keyword_int:3} {minutes}. For the duration, whenever a creature within {keyword_range:30:60:5}{ft} has advantage or disadvantage on a roll, they instead have neither.",
    typeId: "jewelry",
    model: "ItemSlot",
    flavor: null,
    prefix: "Equilibrium",
    suffix: "of Balance",
  },
  {
    mod: "When you hit with this weapon you may roll {1d6}. On a {4+} you Crit for double damage, otherwise your attack deals no damage.",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: null,
    prefix: "Unreliable",
    suffix: "Of the Tiger",
  },
  {
    mod: "An aura of pestilence surrounds you, you may have creatures within {5ft} of you take a {DC 15 CON} save at the start of their turn or take {1d6} {necrotic} damage.",
    typeId: "body",
    model: "ItemSlot",
    flavor: null,
    prefix: "Pestilent",
    suffix: "of the Flies",
  },
  {
    mod: "This armour is especially good looking, {+2 Charisma}.",
    typeId: "body",
    model: "ItemSlot",
    flavor: null,
    prefix: "Charming",
    suffix: "of the Prince",
  },
  {
    mod: "Once per day as an action you may teleport up to {keyword_range:10:30:5}{ft}.",
    typeId: "boots",
    model: "ItemSlot",
    flavor: null,
    prefix: "Aperture",
    suffix: "of the Void",
  },
  {
    mod: "Living creatures hit with this weapon must make a {DC 10 CON} saving throw or be encased in ice until the end of their next turn.",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: null,
    prefix: "Stasis",
    suffix: "Of Stasis",
  },
  {
    mod: "When shattered, this potion explodes in dark energy, dealing {1d12 force} damage to all creatures within {20ft}. The energy is so potent it lingers for 1 minute, dealing {1d4 force} damage to any creature caught in its area at the start of their turn.",
    typeId: "Flask",
    model: "ItemBase",
    flavor: null,
    prefix: "Void",
    suffix: "Of the Void",
  },
  {
    mod: "This weapon has {double} its standard range.",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: null,
    prefix: "Really Long",
    suffix: "of Distance",
  },
  {
    mod: "The duration of negative conditions on you is reduced by {1 round}. (to a minimum of 1)",
    typeId: "helmet",
    model: "ItemSlot",
    flavor: null,
    prefix: "Mithridates",
    suffix: "of Expulsion",
  },
  {
    mod: "The duration of negative conditions on you is reduced by {1 round}. (to a minimum of 1)",
    typeId: "body",
    model: "ItemSlot",
    flavor: null,
    prefix: "Mithridates",
    suffix: "of Expulsion",
  },
  {
    mod: "You gain a {+2} bonus to maintain your concentration on a spell.",
    typeId: "jewelry",
    model: "ItemSlot",
    flavor: null,
    prefix: "Augur",
    suffix: "of the Virtuoso",
  },
  {
    mod: "Once per day, you may pass a {keyword_attribute} saving throw you otherwise would have failed.",
    typeId: "boots",
    model: "ItemSlot",
    flavor: null,
    prefix: "Reformation",
    suffix: "of Reawakening",
  },
  {
    mod: "Once per day, you may pass a {keyword_attribute} saving throw you otherwise would have failed.",
    typeId: "body",
    model: "ItemSlot",
    flavor: null,
    prefix: "Reformation",
    suffix: "of Reawakening",
  },
  {
    mod: "Your {keyword_attribute} score is increased by {+1}.",
    typeId: "helmet",
    model: "ItemSlot",
    flavor: null,
    prefix: "Blessed",
    suffix: "of the Jesuit",
  },
  {
    mod: "Increase all {keyword_damage_type} damage by {10%}",
    typeId: "gloves",
    model: "ItemSlot",
    flavor: null,
    prefix: "Conduit",
    suffix: "of the past",
  },
  {
    mod: "You can walk on your hands with no penalty to your normal movement speed.",
    typeId: "gloves",
    model: "ItemSlot",
    flavor: null,
    prefix: "Jester's",
    suffix: "of Busking",
  },
  {
    mod: "This weapon has a black blade that seems to absorb light. In addition, once per day as a standard action, the wielder can cause the blade to shed darkness in a 30-foot radius. This darkness lasts for 1 minute.",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: null,
    prefix: "Dark",
    suffix: "of the Reaper",
  },
  {
    mod: "A target's soul may be drawn out of their body on a killing blow, permanently giving {+1} to damage rolls per soul. \n{Cursed}: This weapon can only be wielded by an evil creature. Other alignments instead take {+1} damage per soul on hit.",
    typeId: "weapon",
    model: "ItemSlot",
    flavor: null,
    prefix: "",
    suffix: "of the Reaper",
  },
  {
    mod: "Gain advantage on all {keyword_attribute} saving throws.",
    typeId: "helmet",
    model: "ItemSlot",
    prefix: "Guardian's",
    suffix: "of Fortitude",
  },
  {
    mod: "Regenerate {keyword_int} hit points every hour.",
    typeId: "body",
    model: "ItemSlot",
    prefix: "Restorative",
    suffix: "of Vitality",
  },
  {
    mod: "Increase your movement speed by {keyword_int:10} feet.",
    typeId: "boots",
    model: "ItemSlot",
    prefix: "Swift",
    suffix: "of the Wind",
  },
  {
    mod: "Gain advantage on all {keyword_attribute} checks.",
    typeId: "gloves",
    model: "ItemSlot",
    prefix: "Master's",
    suffix: "of Proficiency",
  },
  {
    mod: "Add {keyword_int:4} to all your damage rolls against {keyword_enemy_type} enemies.",
    typeId: "weapon",
    model: "ItemSlot",
    prefix: "Bane",
    suffix: "of the Hunter",
  },
  {
    mod: "Once per day, you may cast the spell 'Cure Wounds' at first level.",
    typeId: "jewelry",
    model: "ItemSlot",
    prefix: "Healing",
    suffix: "of the Light",
  },
  {
    mod: "Add {keyword_int:4} to your Armor Class against ranged attacks.",
    typeId: "shield",
    model: "ItemSlot",
    prefix: "Aegis",
    suffix: "of Deflection",
  },
  {
    mod: "Gain darkvision up to a range of {keyword_range:60,120,20} feet.",
    typeId: "helmet",
    model: "ItemSlot",
    prefix: "Shadow's",
    suffix: "of the Night",
  },
  {
    mod: "Once per day, you can cast 'Invisibility' on yourself.",
    typeId: "cloak",
    model: "ItemSlot",
    prefix: "Ghostly",
    suffix: "of the Unseen",
  },
  {
    mod: "Resistance to {keyword_damage_type} damage.",
    typeId: "body",
    model: "ItemSlot",
    prefix: "Guard",
    suffix: "of the Elements",
  },
  {
    mod: "Add {keyword_int:2} to your Initiative rolls.",
    typeId: "boots",
    model: "ItemSlot",
    prefix: "Quick",
    suffix: "of Readiness",
  },
  {
    mod: "You can breathe underwater indefinitely.",
    typeId: "helmet",
    model: "ItemSlot",
    prefix: "Mariner's",
    suffix: "of the Depths",
  },
  {
    mod: "Increase your carrying capacity by {keyword_int:50} pounds.",
    typeId: "Belt",
    model: "ItemBase",
    prefix: "Brawny",
    suffix: "of Burden",
  },
  {
    mod: "Once per day, you may negate falling damage.",
    typeId: "body",
    model: "ItemSlot",
    prefix: "Feathered",
    suffix: "of the Skylark",
  },
  {
    mod: "Resistance to poison and advantage on saving throws against poison.",
    typeId: "ring",
    model: "ItemBase",
    prefix: "Venomous",
    suffix: "of the Serpent",
  },
  {
    mod: "Gain {keyword_int:2} bonus to your {keyword_attribute} attribute.",
    typeId: "amulet",
    model: "ItemBase",
    prefix: "Enhanced",
    suffix: "of the Wise",
  },
  {
    mod: "Your melee attacks deal an additional {keyword_int:2} fire damage.",
    typeId: "gloves",
    model: "ItemSlot",
    prefix: "Flaming",
    suffix: "of the Inferno",
  },
  {
    mod: "Gain a +{keyword_int:2} bonus to all saving throws.",
    typeId: "body",
    model: "ItemSlot",
    prefix: "Fortified",
    suffix: "of the Protector",
  },
  {
    mod: "You have advantage on Perception checks.",
    typeId: "helmet",
    model: "ItemSlot",
    prefix: "Hawk's",
    suffix: "of Perception",
  },
  {
    mod: "Once per day, you can reroll a failed saving throw.",
    typeId: "jewelry",
    model: "ItemSlot",
    prefix: "Lucky",
    suffix: "of the Fates",
  },
  {
    mod: "Gain a +{keyword_int:2} bonus to your Spell Save DC.",
    typeId: "weapon",
    model: "ItemSlot",
    prefix: "Mystic",
    suffix: "of the Archmage",
  },
  {
    mod: "You can speak, read, and write one additional language of your choice.",
    typeId: "amulet",
    model: "ItemBase",
    prefix: "Polyglot's",
    suffix: "of Understanding",
  },
  {
    mod: "Your ranged attacks have an additional {keyword_int:20} feet range.",
    typeId: "gloves",
    model: "ItemSlot",
    prefix: "Far",
    suffix: "of the Marksman",
  },
  {
    mod: "Increase your maximum HP by {keyword_int:20}. Disadvantage on stealth checks.",
    typeId: "body",
    model: "ItemSlot",
    prefix: "Stalwart",
    suffix: "of Health",
  },
  {
    mod: "You can see in the dark up to 60 feet as if it were bright light.",
    typeId: "helmet",
    model: "ItemSlot",
    prefix: "Darkvision",
    suffix: "of the Nightseer",
  },
  {
    mod: "Your unarmed strikes deal an additional {keyword_int:5} bludgeoning damage.",
    typeId: "gloves",
    model: "ItemSlot",
    prefix: "Pugilist's",
    suffix: "of the Brawler",
  },
  {
    mod: "Increase your walking speed by {keyword_int:10} feet.",
    typeId: "boots",
    model: "ItemSlot",
    prefix: "Swift",
    suffix: "of the Zephyr",
  },
  {
    mod: "You gain {keyword_int:5} to your {STR} checks when attempting to break an object.",
    typeId: "gloves",
    model: "ItemSlot",
    prefix: "Smashing",
    suffix: "of the Colossus",
  },
  {
    mod: "You have advantage on checks to avoid being knocked prone.",
    typeId: "boots",
    model: "ItemSlot",
    prefix: "Steadfast",
    suffix: "of Stability",
  },
  {
    mod: "Once per day, you may force a creature within {keyword_range:30,20} feet to make a {DC 15 Wisdom} saving throw or be frightened until the end of its next turn.",
    typeId: "amulet",
    model: "ItemBase",
    prefix: "Intimidating",
    suffix: "of the Terror",
  },
  {
    mod: "You gain {keyword_int:4} to your Constitution checks when resisting diseases.",
    typeId: "body",
    model: "ItemSlot",
    prefix: "Healthy",
    suffix: "of Vitality",
  },
  {
    mod: "Your melee attacks deal an extra {keyword_int:5} damage to {keyword_enemy_type}.",
    typeId: "ring",
    model: "ItemBase",
    prefix: "Hunting",
    suffix: "of Slaying",
  },
  {
    mod: "Once per day, you may make a creature you touch unable to lie for 1 minute.",
    typeId: "gloves",
    model: "ItemSlot",
    prefix: "Honest",
    suffix: "of Verity",
  },
  {
    mod: "You gain {keyword_int:10} feet bonus to your movement speed when not in combat.",
    typeId: "boots",
    model: "ItemSlot",
    prefix: "Quick",
    suffix: "of the Windrunner",
  },
  {
    mod: "You have advantage on Charisma checks when interacting with {keyword_enemy_type}s.",
    typeId: "amulet",
    model: "ItemBase",
    prefix: "Friendly",
    suffix: "of Diplomacy",
  },
  {
    mod: "Once per day, you can absorb the energy of a single spell targeting you, negating its effect and healing you for {keyword_int:2} hit points per level of the spell.",
    typeId: "ring",
    model: "ItemBase",
    prefix: "Spellward",
    suffix: "of the Arcane Eater",
  },
  {
    mod: "Once per day, you can cause a creature you hit with this weapon to be stunned until the end of its next turn.",
    typeId: "weapon",
    model: "ItemSlot",
    prefix: "Stunning",
    suffix: "of Paralysis",
  },
  {
    mod: "On a successful hit, the target must make a {keyword_attribute_short_check} or be knocked prone.",
    typeId: "weapon",
    model: "ItemSlot",
    prefix: "Toppling",
    suffix: "of the Earthshaker",
  },
  {
    mod: "Once per day, you can cause a creature you hit with this weapon to become frightened until the end of its next turn.",
    typeId: "weapon",
    model: "ItemSlot",
    prefix: "Terrifying",
    suffix: "of Dread",
  },
  {
    mod: "You gain a {keyword_int:5} bonus to attack and damage rolls with this weapon against {keyword_enemy_type}.",
    typeId: "weapon",
    model: "ItemSlot",
    prefix: "Slayer",
    suffix: "of Beasts",
  },
  {
    mod: "When you hit a creature with this weapon, its speed is reduced by {keyword_int:10} feet until the end of its next turn.",
    typeId: "weapon",
    model: "ItemSlot",
    prefix: "Slowing",
    suffix: "of the Glacier",
  },
  {
    mod: "Your attacks with this weapon ignore resistance to {keyword_damage_type} damage.",
    typeId: "weapon",
    model: "ItemSlot",
    prefix: "Penetrating",
    suffix: "of Sundering",
  },
  {
    mod: "Once per day, you can make an attack with this weapon that, if it hits, causes the target to lose the benefits of invisibility and illusions altering its appearance until the end of its next turn.",
    typeId: "weapon",
    model: "ItemSlot",
    prefix: "Revealing",
    suffix: "of Truth",
  },
  {
    mod: "When you score a critical hit with this weapon, the target takes an additional {1d10} {keyword_damage_type} damage.",
    typeId: "weapon",
    model: "ItemSlot",
    prefix: "Crippling",
    suffix: "of Wounding",
  },
  {
    mod: "Your attacks with this weapon deal an extra {1d6} {fire} damage.",
    typeId: "weapon",
    model: "ItemSlot",
    prefix: "Flaming",
    suffix: "of Inferno",
  },
  {
    mod: "Your attacks with this weapon deal an extra {1d6} {cold} damage.",
    typeId: "weapon",
    model: "ItemSlot",
    prefix: "Frost",
    suffix: "of the Icicle",
  },
  {
    mod: "Your attacks with this weapon deal an extra {1d6} {lightning} damage.",
    typeId: "weapon",
    model: "ItemSlot",
    prefix: "Electrifying",
    suffix: "of the Thunderbolt",
  },
  {
    mod: "Your attacks with this weapon deal an extra {1d6} {acid} damage.",
    typeId: "weapon",
    model: "ItemSlot",
    prefix: "Corrosive",
    suffix: "of the Acid Rain",
  },
  {
    mod: "Your attacks with this weapon deal an extra {1d6} {poison} damage.",
    typeId: "weapon",
    model: "ItemSlot",
    prefix: "Venomous",
    suffix: "of the Serpent",
  },
  {
    mod: "Your attacks with this weapon deal an extra {1d6} {necrotic} damage.",
    typeId: "weapon",
    model: "ItemSlot",
    prefix: "Dark",
    suffix: "of the Crypt",
  },
  {
    mod: "Your attacks with this weapon deal an extra {1d6} {radiant} damage.",
    typeId: "weapon",
    model: "ItemSlot",
    prefix: "Luminous",
    suffix: "of the Dawn",
  },
  {
    mod: "Your attacks with this weapon deal an extra {1d6} {psychic} damage.",
    typeId: "weapon",
    model: "ItemSlot",
    prefix: "Mental",
    suffix: "of the Mindstorm",
  },
  {
    mod: "Your attacks with this weapon deal an extra {1d6} {force} damage.",
    typeId: "weapon",
    model: "ItemSlot",
    prefix: "Energetic",
    suffix: "of the Force Wave",
  },
  {
    mod: "Your attacks with this weapon deal an extra {1d6} {thunder} damage.",
    typeId: "weapon",
    model: "ItemSlot",
    prefix: "Resonating",
    suffix: "of the Thunderclap",
  },
  {
    mod: "This weapon critically hits on a roll of 19 or 20. \n{Cursed}: Every time you critically hit, you take {1d4} {necrotic} damage as the weapon drains your life force.",
    typeId: "weapon",
    model: "ItemSlot",
    prefix: "Bloodthirsty",
    suffix: "of the Vampire",
  },
  {
    mod: "This weapon's damage is increased by {2} against creatures of {Good} alignment. \n{Cursed}: {Good} aligned creatures gain advantage when attacking you.",
    typeId: "weapon",
    model: "ItemSlot",
    prefix: "Malevolent",
    suffix: "of Persecution",
  },
  {
    mod: "Once per day, you may choose to deal maximum damage with a successful hit. \n{Cursed}: You also take half this damage as the weapon feeds on your pain.",
    typeId: "weapon",
    model: "ItemSlot",
    prefix: "Merciless",
    suffix: "of Reciprocity",
  },
  {
    mod: "You may attack twice as a single action once per day. \n{Cursed}: After using this feature, you cannot take actions on your next turn as the weapon's power overwhelms you.",
    typeId: "weapon",
    model: "ItemSlot",
    prefix: "Frenzied",
    suffix: "of Exhaustion",
  },
  {
    mod: "Your attacks ignore resistance to {physical} damage. \n{Cursed}: You are vulnerable to all forms of {physical} damage.",
    typeId: "weapon",
    model: "ItemSlot",
    prefix: "Piercing",
    suffix: "of Vulnerability",
  },
  {
    mod: "On a hit, you may choose to deal an additional {1d8} {force} damage once per day. \n{Cursed}: The force damage rebounds, dealing half of it to you.",
    typeId: "weapon",
    model: "ItemSlot",
    prefix: "Explosive",
    suffix: "of Rebound",
  },
  {
    mod: "On a hit, your target must succeed on a {DC 15 Constitution} saving throw or be {stunned} until the start of your next turn. \n{Cursed}: Each time you use this ability, you take {1d6} psychic damage.",
    typeId: "weapon",
    model: "ItemSlot",
    prefix: "Paralyzing",
    suffix: "of Headache",
  },
  {
    mod: "On a successful hit, your target is {marked}, granting you advantage on all attacks against it until the start of your next turn. \n{Cursed}: All creatures have advantage on attack rolls against you until the start of your next turn.",
    typeId: "weapon",
    model: "ItemSlot",
    prefix: "Marking",
    suffix: "of Retaliation",
  },
  {
    mod: "Once per day, you can automatically confirm a hit as a critical hit. \n{Cursed}: After using this ability, all attacks against you are critical hits until the start of your next turn.",
    typeId: "weapon",
    model: "ItemSlot",
    prefix: "Deadly",
    suffix: "of Exposure",
  },
  {
    mod: "Once per day, you may reroll a missed attack. \n{Cursed}: Every time you reroll an attack, you must take a {DC 15 Dexterity} saving throw or fall {prone}.",
    typeId: "weapon",
    model: "ItemSlot",
    prefix: "Persistent",
    suffix: "of Instability",
  },
];

export function getRandomMods(slotName, baseName, n = 1) {
  const lowerSlotName = slotName.toLowerCase();
  const lowerBaseName = baseName.toLowerCase();

  const applicableMods = ITEM_MODS.filter((mod) => {
    return (
      mod.typeId.toLowerCase() === lowerSlotName ||
      mod.typeId.toLowerCase() === lowerBaseName
    );
  });

  if (applicableMods.length === 0) {
    return [];
  }

  let mods = [];
  for (let i = 0; i < n; i++) {
    let randomIndex = Math.floor(Math.random() * applicableMods.length);
    mods.push(applicableMods[randomIndex]);
    applicableMods.splice(randomIndex, 1);

    if (applicableMods.length === 0) {
      break;
    }
  }

  return mods;
}
